	.arch armv7-a
	.eabi_attribute 20, 1
	.eabi_attribute 21, 1
	.eabi_attribute 23, 3
	.eabi_attribute 24, 1
	.eabi_attribute 25, 1
	.eabi_attribute 26, 2
	.eabi_attribute 30, 4
	.eabi_attribute 34, 1
	.eabi_attribute 18, 2
	.file	"mpi_dev.c"
	.text
	.syntax unified
	.syntax unified
	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_node_add_in_watcher:					
	.asciz 	"mpi_node_add_in_watcher"					
__kstrtabns_mpi_node_add_in_watcher:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_node_add_in_filter:					
	.asciz 	"mpi_node_add_in_filter"					
__kstrtabns_mpi_node_add_in_filter:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_node_add_out_watcher:					
	.asciz 	"mpi_node_add_out_watcher"					
__kstrtabns_mpi_node_add_out_watcher:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_node_add_out_filter:					
	.asciz 	"mpi_node_add_out_filter"					
__kstrtabns_mpi_node_add_out_filter:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_node_del_in_watcher:					
	.asciz 	"mpi_node_del_in_watcher"					
__kstrtabns_mpi_node_del_in_watcher:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_node_del_in_filter:					
	.asciz 	"mpi_node_del_in_filter"					
__kstrtabns_mpi_node_del_in_filter:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_node_del_out_watcher:					
	.asciz 	"mpi_node_del_out_watcher"					
__kstrtabns_mpi_node_del_out_watcher:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_node_del_out_filter:					
	.asciz 	"mpi_node_del_out_filter"					
__kstrtabns_mpi_node_del_out_filter:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_node_enable_auto_streamon:					
	.asciz 	"mpi_node_enable_auto_streamon"					
__kstrtabns_mpi_node_enable_auto_streamon:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_node_pick_in_buffer:					
	.asciz 	"mpi_node_pick_in_buffer"					
__kstrtabns_mpi_node_pick_in_buffer:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_node_pick_out_buffer:					
	.asciz 	"mpi_node_pick_out_buffer"					
__kstrtabns_mpi_node_pick_out_buffer:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_node_release_buffer_flag:					
	.asciz 	"mpi_node_release_buffer_flag"					
__kstrtabns_mpi_node_release_buffer_flag:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_node_set_frame_rate:					
	.asciz 	"mpi_node_set_frame_rate"					
__kstrtabns_mpi_node_set_frame_rate:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_node_force_lost_frame:					
	.asciz 	"mpi_node_force_lost_frame"					
__kstrtabns_mpi_node_force_lost_frame:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_node_streamon:					
	.asciz 	"mpi_node_streamon"					
__kstrtabns_mpi_node_streamon:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_node_streamoff:					
	.asciz 	"mpi_node_streamoff"					
__kstrtabns_mpi_node_streamoff:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_node_stream_pause:					
	.asciz 	"mpi_node_stream_pause"					
__kstrtabns_mpi_node_stream_pause:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_node_buffer_in:					
	.asciz 	"mpi_node_buffer_in"					
__kstrtabns_mpi_node_buffer_in:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_node_buffer_out:					
	.asciz 	"mpi_node_buffer_out"					
__kstrtabns_mpi_node_buffer_out:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_node_get_in_buffer:					
	.asciz 	"mpi_node_get_in_buffer"					
__kstrtabns_mpi_node_get_in_buffer:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_node_get_out_buffer:					
	.asciz 	"mpi_node_get_out_buffer"					
__kstrtabns_mpi_node_get_out_buffer:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_node_request_buf:					
	.asciz 	"mpi_node_request_buf"					
__kstrtabns_mpi_node_request_buf:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_node_flush:					
	.asciz 	"mpi_node_flush"					
__kstrtabns_mpi_node_flush:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_node_unbind:					
	.asciz 	"mpi_node_unbind"					
__kstrtabns_mpi_node_unbind:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_node_bind:					
	.asciz 	"mpi_node_bind"					
__kstrtabns_mpi_node_bind:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_node_set_params:					
	.asciz 	"mpi_node_set_params"					
__kstrtabns_mpi_node_set_params:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_node_destroy:					
	.asciz 	"mpi_node_destroy"					
__kstrtabns_mpi_node_destroy:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_dev_create_node_with_params:					
	.asciz 	"mpi_dev_create_node_with_params"					
__kstrtabns_mpi_dev_create_node_with_params:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_dev_request_job:					
	.asciz 	"mpi_dev_request_job"					
__kstrtabns_mpi_dev_request_job:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_dev_request_job_for_node:					
	.asciz 	"mpi_dev_request_job_for_node"					
__kstrtabns_mpi_dev_request_job_for_node:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_dev_run_job:					
	.asciz 	"mpi_dev_run_job"					
__kstrtabns_mpi_dev_run_job:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_dev_unregister:					
	.asciz 	"mpi_dev_unregister"					
__kstrtabns_mpi_dev_unregister:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_dev_register:					
	.asciz 	"mpi_dev_register"					
__kstrtabns_mpi_dev_register:					
	.asciz 	""					
	.previous						

	.thumb
	.syntax unified
	.align	1
	.global	mpi_node_force_lost_frame
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_node_force_lost_frame, %function
mpi_node_force_lost_frame:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	@ link register save eliminated.
	bic	r1, r1, r1, asr #31
	str	r1, [r0]
	movs	r0, #0
	bx	lr
	.fnend
	.size	mpi_node_force_lost_frame, .-mpi_node_force_lost_frame
	.align	1
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_node_cleanup_in_buffer, %function
mpi_node_cleanup_in_buffer:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r3, r4, r5, lr}
	.save {r3, r4, r5, lr}
	mov	r4, r0
	cbnz	r1, .L3
	ldr	r3, [r0, #324]
	cbnz	r3, .L2
	ldr	r3, [r0, #328]
	cbnz	r3, .L2
.L3:
	.syntax unified
@ 29 "./arch/arm/include/asm/irqflags.h" 1
		mrs	r5, cpsr	@ arch_local_irq_save
	cpsid	i
@ 0 "" 2
	.thumb
	.syntax unified
	ldr	r0, [r4, #348]
	cbz	r0, .L5
	movs	r1, #0
	bl	mpi_queue_destroy
	movs	r3, #0
	str	r3, [r4, #348]
.L5:
	.syntax unified
@ 171 "./arch/arm/include/asm/irqflags.h" 1
		msr	cpsr_c, r5	@ local_irq_restore
@ 0 "" 2
	.thumb
	.syntax unified
.L2:
	pop	{r3, r4, r5, pc}
	.fnend
	.size	mpi_node_cleanup_in_buffer, .-mpi_node_cleanup_in_buffer
	.align	1
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_node_cleanup_out_buffer, %function
mpi_node_cleanup_out_buffer:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r3, r4, r5, lr}
	.save {r3, r4, r5, lr}
	mov	r4, r0
	cbnz	r1, .L10
	ldr	r3, [r0, #336]
	cbnz	r3, .L9
	ldr	r3, [r0, #340]
	cbnz	r3, .L9
.L10:
	.syntax unified
@ 29 "./arch/arm/include/asm/irqflags.h" 1
		mrs	r5, cpsr	@ arch_local_irq_save
	cpsid	i
@ 0 "" 2
	.thumb
	.syntax unified
	ldr	r0, [r4, #352]
	cbz	r0, .L12
	movs	r1, #0
	bl	mpi_queue_destroy
	movs	r3, #0
	str	r3, [r4, #352]
.L12:
	.syntax unified
@ 171 "./arch/arm/include/asm/irqflags.h" 1
		msr	cpsr_c, r5	@ local_irq_restore
@ 0 "" 2
	.thumb
	.syntax unified
.L9:
	pop	{r3, r4, r5, pc}
	.fnend
	.size	mpi_node_cleanup_out_buffer, .-mpi_node_cleanup_out_buffer
	.align	1
	.global	mpi_node_streamon
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_node_streamon, %function
mpi_node_streamon:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r0, r1, r2, r3, r4, r5, r6, lr}
	.save {r4, r5, r6, lr}
	.pad #16
	mov	r4, r0
	ldr	r3, [r0, #12]
	ldr	r6, [r0, #44]
	tst	r3, #3072
	bne	.L23
	cbz	r0, .L18
	ldr	r3, [r0, #12]
	and	r3, r3, #6
	cmp	r3, #2
	beq	.L19
.L18:
.L23:
	mov	r5, #-1
	b	.L16
.L19:
	bl	mpi_obj_ref
	ldr	r5, [r4, #12]
	ands	r5, r5, #4096
	beq	.L20
.L22:
	movs	r5, #0
.L21:
	mov	r0, r4
	bl	mpi_obj_unref
.L16:
	mov	r0, r5
	add	sp, sp, #16
	@ sp needed
	pop	{r4, r5, r6, pc}
.L20:
	ldr	r3, [r4]
	movs	r1, #4
	ldr	r2, .L30
	mov	r0, r5
	str	r3, [sp, #8]
	ldr	r3, [r4, #44]
	ldr	r3, [r3, #44]
	str	r3, [sp, #4]
	mov	r3, #364
	str	r3, [sp]
	ldr	r3, .L30+4
	bl	vlog
	ldr	r3, [r6, #80]
	cmp	r3, #0
	beq	.L22
	mov	r3, #366
	ldr	r2, .L30+8
	str	r3, [sp]
	movs	r1, #4
	ldr	r3, .L30+4
	mov	r0, r5
	bl	vlog
	mov	r2, r5
	ldr	r3, [r6, #80]
	movs	r1, #5
	mov	r0, r4
	blx	r3
	mov	r5, r0
	cmp	r0, #0
	bne	.L21
	ldr	r3, [r4, #12]
	orr	r3, r3, #4096
	str	r3, [r4, #12]
	b	.L21
.L31:
	.align	2
.L30:
	.word	.LC0
	.word	.LANCHOR0
	.word	.LC1
	.fnend
	.size	mpi_node_streamon, .-mpi_node_streamon
	.align	1
	.global	mpi_node_stream_pause
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_node_stream_pause, %function
mpi_node_stream_pause:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r4, lr}
	.save {r4, lr}
	mov	r4, r0
	cbz	r0, .L33
	ldr	r3, [r0, #12]
	and	r3, r3, #6
	cmp	r3, #2
	beq	.L34
.L33:
	mov	r0, #-1
.L32:
	pop	{r4, pc}
.L34:
.L36:
	bl	mpi_obj_ref
	ldr	r3, [r4, #12]
	mov	r0, r4
	lsls	r2, r3, #19
	itt	mi
	bicmi	r3, r3, #4096
	strmi	r3, [r4, #12]
	bl	mpi_obj_unref
	movs	r0, #0
	b	.L32
	.fnend
	.size	mpi_node_stream_pause, .-mpi_node_stream_pause
	.align	1
	.global	mpi_node_streamoff
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_node_streamoff, %function
mpi_node_streamoff:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r4, r5, lr}
	.save {r4, r5, lr}
	mov	r4, r0
	.pad #20
	sub	sp, sp, #20
	ldr	r5, [r0, #44]
	cbz	r0, .L44
	ldr	r3, [r0, #12]
	and	r3, r3, #6
	cmp	r3, #2
	beq	.L45
.L44:
	mov	r0, #-1
.L43:
	add	sp, sp, #20
	@ sp needed
	pop	{r4, r5, pc}
.L45:
	bl	mpi_obj_ref
	ldr	r3, [r4, #12]
	lsls	r3, r3, #19
	bpl	.L47
	ldr	r3, [r4]
	movs	r1, #5
	ldr	r2, .L58
	movs	r0, #0
	str	r3, [sp, #8]
	ldr	r3, [r4, #44]
	ldr	r3, [r3, #44]
	str	r3, [sp, #4]
	movw	r3, #397
	str	r3, [sp]
	ldr	r3, .L58+4
	bl	vlog
	ldr	r3, [r4, #12]
	bic	r3, r3, #4096
	str	r3, [r4, #12]
	ldr	r3, [r5, #80]
	cbz	r3, .L48
	movs	r2, #0
	movs	r1, #6
	mov	r0, r4
	blx	r3
.L48:
	.syntax unified
@ 29 "./arch/arm/include/asm/irqflags.h" 1
		mrs	r5, cpsr	@ arch_local_irq_save
	cpsid	i
@ 0 "" 2
	.thumb
	.syntax unified
	add	r0, r4, #356
	bl	complete_all
	add	r0, r4, #368
	bl	complete_all
	.syntax unified
@ 171 "./arch/arm/include/asm/irqflags.h" 1
		msr	cpsr_c, r5	@ local_irq_restore
@ 0 "" 2
	.thumb
	.syntax unified
.L47:
	mov	r0, r4
	bl	mpi_obj_unref
	movs	r0, #0
	b	.L43
.L59:
	.align	2
.L58:
	.word	.LC2
	.word	.LANCHOR0+18
	.fnend
	.size	mpi_node_streamoff, .-mpi_node_streamoff
	.align	1
	.global	mpi_node_flush
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_node_flush, %function
mpi_node_flush:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r4, r5, r6, r7, lr}
	.save {r4, r5, r6, r7, lr}
	mov	r4, r0
	.pad #20
	sub	sp, sp, #20
	mov	r5, r1
	ldr	r7, [r0, #44]
	.syntax unified
@ 29 "./arch/arm/include/asm/irqflags.h" 1
		mrs	r2, cpsr	@ arch_local_irq_save
	cpsid	i
@ 0 "" 2
	.thumb
	.syntax unified
	ldr	r3, [r0, #12]
	add	r6, r0, #312
	ands	r1, r3, #2048
	beq	.L61
	.syntax unified
@ 171 "./arch/arm/include/asm/irqflags.h" 1
		msr	cpsr_c, r2	@ local_irq_restore
@ 0 "" 2
	.thumb
	.syntax unified
	mov	r0, r6
	bl	wait_for_completion
.L62:
	movs	r0, #0
	add	sp, sp, #20
	@ sp needed
	pop	{r4, r5, r6, r7, pc}
.L61:
	orr	r3, r3, #2048
	str	r1, [r0, #312]
	str	r3, [r0, #12]
	.syntax unified
@ 171 "./arch/arm/include/asm/irqflags.h" 1
		msr	cpsr_c, r2	@ local_irq_restore
@ 0 "" 2
	.thumb
	.syntax unified
	ldr	r3, [r0, #12]
	lsls	r3, r3, #19
	bpl	.L63
	bl	mpi_node_streamoff
.L63:
	ldr	r3, [r4]
	movs	r1, #5
	ldr	r2, .L77
	movs	r0, #0
	str	r3, [sp, #8]
	ldr	r3, [r7, #44]
	str	r3, [sp, #4]
	mov	r3, #760
	str	r3, [sp]
	ldr	r3, .L77+4
	bl	vlog
	ldr	r0, [r4, #308]
	cbz	r0, .L64
	movs	r2, #0
	mov	r1, r5
	bl	mpi_queue_flush
.L64:
	ldr	r3, [r7, #80]
	cbz	r3, .L65
	cbz	r5, .L66
	movs	r2, #0
	movs	r1, #3
.L76:
	mov	r0, r4
	blx	r3
.L65:
	.syntax unified
@ 29 "./arch/arm/include/asm/irqflags.h" 1
		mrs	r5, cpsr	@ arch_local_irq_save
	cpsid	i
@ 0 "" 2
	.thumb
	.syntax unified
	mov	r0, r6
	bl	complete_all
	ldr	r3, [r4, #12]
	bic	r3, r3, #2048
	str	r3, [r4, #12]
	.syntax unified
@ 171 "./arch/arm/include/asm/irqflags.h" 1
		msr	cpsr_c, r5	@ local_irq_restore
@ 0 "" 2
	.thumb
	.syntax unified
	b	.L62
.L66:
	mov	r2, r5
	movs	r1, #2
	b	.L76
.L78:
	.align	2
.L77:
	.word	.LC3
	.word	.LANCHOR0+37
	.fnend
	.size	mpi_node_flush, .-mpi_node_flush
	.align	1
	.global	mpi_node_unbind
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_node_unbind, %function
mpi_node_unbind:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r4, r5, lr}
	.save {r4, r5, lr}
	.pad #28
	sub	sp, sp, #28
	ldr	r3, [r1]
	mov	r4, r1
	ldr	r2, .L88
	mov	r5, r0
	str	r3, [sp, #16]
	ldr	r3, [r1, #44]
	movs	r1, #5
	ldr	r3, [r3, #44]
	str	r3, [sp, #12]
	ldr	r3, [r0]
	str	r3, [sp, #8]
	ldr	r3, [r0, #44]
	movs	r0, #0
	ldr	r3, [r3, #44]
	str	r3, [sp, #4]
	movw	r3, #811
	str	r3, [sp]
	ldr	r3, .L88+4
	bl	vlog
	movs	r1, #1
	mov	r0, r4
	bl	mpi_node_flush
	mov	r0, r4
	bl	mpi_node_streamoff
	ldr	r3, [r4, #12]
	lsls	r2, r3, #18
	bpl	.L79
	bic	r3, r3, #8192
	str	r3, [r4, #12]
	ldr	r3, [r4, #44]
	ldr	r3, [r3, #72]
	cbz	r3, .L82
	movs	r1, #0
	ldr	r0, [r4, #288]
	blx	r3
	str	r0, [r4, #288]
.L82:
	mov	r1, r4
	add	r0, r5, #300
	bl	mpi_list_del_obj_rcu
	cbnz	r0, .L83
	mov	r0, r4
	bl	mpi_obj_unref
.L83:
	mov	r1, r5
	add	r0, r4, #292
	bl	mpi_list_del_obj_rcu
	cbnz	r0, .L79
	mov	r0, r5
	add	sp, sp, #28
	@ sp needed
	pop	{r4, r5, lr}
	b	mpi_obj_unref
.L79:
	add	sp, sp, #28
	@ sp needed
	pop	{r4, r5, pc}
.L89:
	.align	2
.L88:
	.word	.LC4
	.word	.LANCHOR0+52
	.fnend
	.size	mpi_node_unbind, .-mpi_node_unbind
	.align	1
	.global	mpi_node_bind
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_node_bind, %function
mpi_node_bind:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r4, r5, r6, lr}
	.save {r4, r5, r6, lr}
	mov	r5, r0
	.pad #24
	sub	sp, sp, #24
	mov	r4, r1
	cbz	r0, .L91
	ldr	r3, [r0, #12]
	and	r3, r3, #6
	cmp	r3, #2
	beq	.L92
.L91:
	mov	r6, #-1
.L90:
	mov	r0, r6
	add	sp, sp, #24
	@ sp needed
	pop	{r4, r5, r6, pc}
.L92:
	bl	mpi_obj_ref
	cbz	r4, .L94
	ldr	r3, [r4, #12]
	and	r3, r3, #6
	cmp	r3, #2
	beq	.L95
.L94:
	mov	r6, #-1
.L96:
	mov	r0, r5
	bl	mpi_obj_unref
	b	.L90
.L95:
	mov	r0, r4
	bl	mpi_obj_ref
	ldr	r3, [r5, #12]
	lsls	r2, r3, #21
	bmi	.L101
	ldr	r3, [r4, #12]
	tst	r3, #9216
	bne	.L101
	mov	r1, r4
	add	r0, r5, #300
	bl	mpi_list_add_tail_obj_rcu
	mov	r0, r5
	bl	mpi_obj_ref
	mov	r1, r5
	add	r0, r4, #292
	bl	mpi_list_add_tail_obj_rcu
	mov	r0, r4
	bl	mpi_obj_ref
	ldr	r3, [r4, #12]
	orr	r3, r3, #8192
	str	r3, [r4, #12]
	ldr	r3, [r4, #44]
	ldr	r3, [r3, #72]
	cbz	r3, .L98
	mov	r1, r5
	ldr	r0, [r4, #288]
	blx	r3
	str	r0, [r4, #288]
.L98:
	ldr	r3, [r4]
	movs	r1, #5
	ldr	r2, .L115
	movs	r0, #0
	str	r3, [sp, #16]
	ldr	r3, [r4, #44]
	ldr	r3, [r3, #44]
	str	r3, [sp, #12]
	ldr	r3, [r5]
	str	r3, [sp, #8]
	ldr	r3, [r5, #44]
	ldr	r3, [r3, #44]
	str	r3, [sp, #4]
	movw	r3, #874
	str	r3, [sp]
	ldr	r3, .L115+4
	bl	vlog
	ldr	r3, [r4, #12]
	lsls	r3, r3, #17
	bpl	.L99
	mov	r0, r4
	bl	mpi_node_streamon
.L99:
	ldr	r6, [r5, #12]
	ands	r6, r6, #16384
	beq	.L97
	mov	r0, r5
	movs	r6, #0
	bl	mpi_node_streamon
.L97:
	mov	r0, r4
	bl	mpi_obj_unref
	b	.L96
.L101:
	mov	r6, #-1
	b	.L97
.L116:
	.align	2
.L115:
	.word	.LC5
	.word	.LANCHOR0+68
	.fnend
	.size	mpi_node_bind, .-mpi_node_bind
	.align	1
	.global	mpi_node_set_params
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_node_set_params, %function
mpi_node_set_params:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r4, r5, r6, lr}
	.save {r4, r5, r6, lr}
	mov	r4, r0
	mov	r6, r1
	cbz	r0, .L118
	ldr	r3, [r0, #12]
	and	r3, r3, #6
	cmp	r3, #2
	beq	.L119
.L118:
	mov	r5, #-1
.L117:
	mov	r0, r5
	pop	{r4, r5, r6, pc}
.L119:
	bl	mpi_obj_ref
	ldr	r3, [r4, #44]
	cbz	r3, .L121
	ldr	r3, [r3, #80]
	cbz	r3, .L121
	mov	r2, r6
	movs	r1, #4
	mov	r0, r4
	blx	r3
	mov	r5, r0
	cbnz	r0, .L121
	ldr	r0, [r4, #80]
	cbz	r0, .L122
	bl	kfree
.L122:
	str	r6, [r4, #80]
.L121:
	mov	r0, r4
	bl	mpi_obj_unref
	b	.L117
	.fnend
	.size	mpi_node_set_params, .-mpi_node_set_params
	.align	1
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	_mpi_job_discard, %function
_mpi_job_discard:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r4, lr}
	.save {r4, lr}
	movs	r1, #1
	mov	r4, r0
	bl	mpi_job_cancel
	mov	r0, r4
	pop	{r4, lr}
	b	mpi_obj_unref
	.fnend
	.size	_mpi_job_discard, .-_mpi_job_discard
	.align	1
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	__init_completion, %function
__init_completion:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	@ link register save eliminated.
	movs	r3, #0
	ldr	r2, .L137
	str	r3, [r0], #4
	ldr	r1, .L137+4
	b	__init_swait_queue_head
.L138:
	.align	2
.L137:
	.word	.LANCHOR1
	.word	.LC6
	.fnend
	.size	__init_completion, .-__init_completion
	.align	1
	.global	mpi_dev_run_job
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_dev_run_job, %function
mpi_dev_run_job:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r3, r4, r5, r6, r7, r8, r9, lr}
	.save {r3, r4, r5, r6, r7, r8, r9, lr}
	mov	r8, r0
	mov	r6, r1
	cbz	r0, .L140
	ldr	r3, [r0, #12]
	and	r3, r3, #6
	cmp	r3, #2
	beq	.L141
.L140:
	movs	r4, #0
.L139:
	mov	r0, r4
	pop	{r3, r4, r5, r6, r7, r8, r9, pc}
.L141:
	mov	r9, r0
	movs	r5, #0
	ldr	r4, [r9, #88]!
	subs	r4, r4, #48
.L143:
	add	r3, r4, #48
	cmp	r3, r9
	bne	.L145
	mov	r2, r6
	movs	r1, #0
	ldr	r0, [r8, #84]
	bl	mpi_job_pool_choose_job
	mov	r4, r0
	cbz	r0, .L146
	cbz	r5, .L147
	cbz	r6, .L147
	mov	r1, r5
	blx	r6
	bics	r4, r4, r0, asr #32
	it	cs
	movcs	r4, r5
.L147:
	ldr	r3, [r4, #48]
	cbz	r3, .L180
	ldr	r2, [r3, #12]
	and	r2, r2, #6
	cmp	r2, #2
	beq	.L150
.L180:
	mov	r0, r4
	bl	mpi_job_set_running
	cmp	r0, #0
	bge	.L148
	b	.L153
.L145:
	ldr	r0, [r4, #308]
	cbz	r0, .L144
	bl	mpi_queue_front_obj
	mov	r7, r0
	cbz	r0, .L144
	ldr	r3, [r0, #68]
	cmp	r3, #2
	bne	.L144
	cbz	r5, .L154
	cbz	r6, .L144
	mov	r1, r0
	mov	r0, r5
	blx	r6
	bics	r5, r5, r0, asr #32
	it	cs
	movcs	r5, r7
.L144:
	ldr	r4, [r4, #48]
	subs	r4, r4, #48
	b	.L143
.L154:
	mov	r5, r0
	b	.L144
.L146:
	cbnz	r5, .L155
.L153:
	movs	r4, #0
.L148:
	b	.L139
.L155:
	mov	r4, r5
	b	.L147
.L150:
	ldr	r0, [r3, #308]
	cbz	r0, .L152
	mov	r1, r4
	bl	mpi_queue_try_pop_obj
	cbnz	r0, .L152
	b	.L153
.L152:
	mov	r0, r4
	bl	mpi_obj_unref
	b	.L180
	.fnend
	.size	mpi_dev_run_job, .-mpi_dev_run_job
	.align	1
	.global	mpi_dev_register
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_dev_register, %function
mpi_dev_register:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r0, r1, r2, r4, r5, lr}
	.save {r4, r5, lr}
	.pad #12
	add	r3, r0, #88
	mov	r4, r0
	str	r3, [r0, #88]
	str	r3, [r0, #92]
	mov	r5, r1
	mov	r0, r2
	mov	r1, #3264
	bl	kstrdup
	movs	r3, #0
	mov	r1, r3
	orr	r2, r5, #64
	str	r0, [r4, #44]
	mov	r0, r4
	bl	mpi_obj_register
	movs	r1, #10
	mov	r0, r4
	bl	mpi_job_pool_create
	str	r0, [r4, #84]
	cbnz	r0, .L182
	mov	r0, r4
	bl	mpi_obj_unregister
	mov	r0, #-1
.L181:
	add	sp, sp, #12
	@ sp needed
	pop	{r4, r5, pc}
.L182:
	ldr	r3, [r4, #44]
	movs	r1, #5
	ldr	r2, .L184
	movs	r0, #0
	str	r3, [sp, #4]
	movw	r3, #1250
	str	r3, [sp]
	ldr	r3, .L184+4
	bl	vlog
	movs	r0, #0
	b	.L181
.L185:
	.align	2
.L184:
	.word	.LC7
	.word	.LANCHOR0+82
	.fnend
	.size	mpi_dev_register, .-mpi_dev_register
	.align	1
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	count_frame_rate.part.1, %function
count_frame_rate.part.1:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	ldr	r3, [r0, #124]
	ldr	r2, [r0, #128]
	adds	r3, r3, #1
	str	r3, [r0, #124]
	push	{r4, lr}
	.save {r4, lr}
	adds	r3, r2, #1
	str	r3, [r0, #128]
	cbz	r1, .L187
	ldr	r3, [r0, #132]
	adds	r3, r3, #1
	str	r3, [r0, #132]
.L187:
	ldr	r1, .L192
	ldr	r4, [r0, #140]
	ldr	r3, [r1]
	rsb	r3, r3, #100
	cmn	r3, r4
	itttt	mi
	ldrmi	r3, [r1]
	strdmi	r2, r3, [r0, #136]
	movmi	r3, #0
	strmi	r3, [r0, #128]
	pop	{r4, pc}
.L193:
	.align	2
.L192:
	.word	jiffies
	.fnend
	.size	count_frame_rate.part.1, .-count_frame_rate.part.1
	.global	__aeabi_idivmod
	.global	__aeabi_uidivmod
	.align	1
	.global	mpi_node_set_frame_rate
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_node_set_frame_rate, %function
mpi_node_set_frame_rate:
	.fnstart
	@ args = 0, pretend = 0, frame = 40
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r4, r5, r6, r7, r8, r9, r10, lr}
	.save {r4, r5, r6, r7, r8, r9, r10, lr}
	mov	r5, r2
	ldr	r2, .L225
	.pad #40
	sub	sp, sp, #40
	subs	r7, r1, #0
	mov	r6, r0
	ldr	r4, [r2]
	mov	r8, r2
	str	r4, [sp, #36]
	blt	.L215
	cmp	r0, r7
	blt	.L215
	subs	r2, r0, #1
	cmp	r2, #29
	bhi	.L215
	cbnz	r7, .L196
	add	r6, r6, r5
	movs	r3, #1
.L197:
	strb	r3, [r5], #1
	cmp	r6, r5
	bne	.L197
.L203:
	movs	r0, #0
.L194:
	ldr	r2, [sp, #36]
	ldr	r3, [r8]
	cmp	r2, r3
	beq	.L212
	bl	__stack_chk_fail
.L196:
	str	r0, [r3]
	bl	__aeabi_idivmod
	mov	r9, r0
	mov	r4, r1
	cbnz	r1, .L198
.L199:
	mov	r0, r4
	mov	r1, r9
	bl	__aeabi_idivmod
	adds	r1, r1, #0
	it	ne
	movne	r1, #1
	strb	r1, [r5, r4]
	adds	r4, r4, #1
	cmp	r6, r4
	bne	.L199
	b	.L203
.L198:
	subs	r4, r6, r7
	mov	r0, r6
	mov	r1, r4
	bl	__aeabi_idivmod
	mov	r10, r0
	mov	r9, r1
	cbnz	r1, .L201
.L202:
	mov	r0, r9
	mov	r1, r10
	bl	__aeabi_idivmod
	clz	r1, r1
	lsrs	r1, r1, #5
	strb	r1, [r5, r9]
	add	r9, r9, #1
	cmp	r6, r9
	bne	.L202
	b	.L203
.L201:
	cmp	r6, r7
	ble	.L203
	add	r2, sp, #6
	movs	r3, #0
	mov	r0, r3
	mov	r1, r2
.L205:
	adds	r3, r3, #1
	strb	r0, [r1], #1
	cmp	r7, r3
	bgt	.L205
.L206:
	mov	r1, r2
	movs	r3, #0
.L208:
	adds	r3, r3, #1
	ldrb	r0, [r1]	@ zero_extendqisi2
	cmp	r3, r4
	add	r0, r0, #1
	strb	r0, [r1], #1
	beq	.L207
	cmp	r7, r3
	bgt	.L208
.L207:
	subs	r4, r4, r3
	bne	.L206
	mov	r3, r4
	mov	ip, r4
	mov	lr, #1
.L211:
	ldrb	r0, [r2], #1	@ zero_extendqisi2
	adds	r6, r3, #1
	strb	ip, [r5, r3]
	add	r3, r3, r5
	movs	r1, #0
.L209:
	cmp	r1, r0
	blt	.L210
	adds	r4, r4, #1
	adds	r3, r6, r0
	cmp	r7, r4
	add	r1, r5, r3
	bgt	.L211
	movs	r3, #0
	strb	r3, [r1]
	b	.L203
.L210:
	strb	lr, [r3, #1]!
	adds	r1, r1, #1
	b	.L209
.L215:
	mov	r0, #-1
	b	.L194
.L212:
	add	sp, sp, #40
	@ sp needed
	pop	{r4, r5, r6, r7, r8, r9, r10, pc}
.L226:
	.align	2
.L225:
	.word	__stack_chk_guard
	.fnend
	.size	mpi_node_set_frame_rate, .-mpi_node_set_frame_rate
	.align	1
	.global	mpi_node_add_in_watcher
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_node_add_in_watcher, %function
mpi_node_add_in_watcher:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r0, r1, r2, r3, r4, r5, r6, lr}
	.save {r4, r5, r6, lr}
	.pad #16
	mov	r4, r0
	mov	r5, r1
	cbz	r0, .L238
	ldr	r3, [r0, #12]
	and	r3, r3, #6
	cmp	r3, #2
	beq	.L229
.L238:
	add	sp, sp, #16
	@ sp needed
	pop	{r4, r5, r6, pc}
.L229:
	str	r1, [sp, #12]
	movs	r1, #5
	ldr	r3, [r0]
	ldr	r2, .L239
	str	r3, [sp, #8]
	ldr	r3, [r0, #44]
	movs	r0, #0
	ldr	r3, [r3, #44]
	str	r3, [sp, #4]
	movs	r3, #202
	str	r3, [sp]
	ldr	r3, .L239+4
	bl	vlog
	.syntax unified
@ 29 "./arch/arm/include/asm/irqflags.h" 1
		mrs	r6, cpsr	@ arch_local_irq_save
	cpsid	i
@ 0 "" 2
	.thumb
	.syntax unified
	ldr	r3, [r4, #324]
	cmp	r5, #0
	add	r3, r3, #1
	str	r3, [r4, #324]
	ble	.L231
	cbz	r3, .L231
	ldr	r2, .L239+8
	movs	r1, #4
	mov	r0, r5
	bl	mpi_queue_create
	movs	r3, #0
	str	r5, [r4, #388]
	str	r3, [r4, #396]
	str	r0, [r4, #348]
.L231:
	.syntax unified
@ 171 "./arch/arm/include/asm/irqflags.h" 1
		msr	cpsr_c, r6	@ local_irq_restore
@ 0 "" 2
	.thumb
	.syntax unified
	b	.L238
.L240:
	.align	2
.L239:
	.word	.LC8
	.word	.LANCHOR0+99
	.word	mpi_obj_unref
	.fnend
	.size	mpi_node_add_in_watcher, .-mpi_node_add_in_watcher
	.align	1
	.global	mpi_node_add_in_filter
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_node_add_in_filter, %function
mpi_node_add_in_filter:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r0, r1, r2, r3, r4, r5, r6, lr}
	.save {r4, r5, r6, lr}
	.pad #16
	mov	r4, r0
	mov	r5, r1
	cbz	r0, .L252
	ldr	r3, [r0, #12]
	and	r3, r3, #6
	cmp	r3, #2
	beq	.L243
.L252:
	add	sp, sp, #16
	@ sp needed
	pop	{r4, r5, r6, pc}
.L243:
	str	r1, [sp, #12]
	movs	r1, #5
	ldr	r3, [r0]
	ldr	r2, .L253
	str	r3, [sp, #8]
	ldr	r3, [r0, #44]
	movs	r0, #0
	ldr	r3, [r3, #44]
	str	r3, [sp, #4]
	movs	r3, #203
	str	r3, [sp]
	ldr	r3, .L253+4
	bl	vlog
	.syntax unified
@ 29 "./arch/arm/include/asm/irqflags.h" 1
		mrs	r6, cpsr	@ arch_local_irq_save
	cpsid	i
@ 0 "" 2
	.thumb
	.syntax unified
	ldr	r3, [r4, #328]
	cmp	r5, #0
	add	r3, r3, #1
	str	r3, [r4, #328]
	ble	.L245
	ldr	r3, [r4, #324]
	cbz	r3, .L245
	ldr	r2, .L253+8
	movs	r1, #4
	mov	r0, r5
	bl	mpi_queue_create
	movs	r3, #0
	str	r5, [r4, #388]
	str	r3, [r4, #396]
	str	r0, [r4, #348]
.L245:
	.syntax unified
@ 171 "./arch/arm/include/asm/irqflags.h" 1
		msr	cpsr_c, r6	@ local_irq_restore
@ 0 "" 2
	.thumb
	.syntax unified
	b	.L252
.L254:
	.align	2
.L253:
	.word	.LC9
	.word	.LANCHOR0+123
	.word	mpi_obj_unref
	.fnend
	.size	mpi_node_add_in_filter, .-mpi_node_add_in_filter
	.align	1
	.global	mpi_node_add_out_watcher
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_node_add_out_watcher, %function
mpi_node_add_out_watcher:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r0, r1, r2, r3, r4, r5, r6, lr}
	.save {r4, r5, r6, lr}
	.pad #16
	mov	r4, r0
	mov	r5, r1
	cbz	r0, .L266
	ldr	r3, [r0, #12]
	and	r3, r3, #6
	cmp	r3, #2
	beq	.L257
.L266:
	add	sp, sp, #16
	@ sp needed
	pop	{r4, r5, r6, pc}
.L257:
	str	r1, [sp, #12]
	movs	r1, #5
	ldr	r3, [r0]
	ldr	r2, .L267
	str	r3, [sp, #8]
	ldr	r3, [r0, #44]
	movs	r0, #0
	ldr	r3, [r3, #44]
	str	r3, [sp, #4]
	movs	r3, #204
	str	r3, [sp]
	ldr	r3, .L267+4
	bl	vlog
	.syntax unified
@ 29 "./arch/arm/include/asm/irqflags.h" 1
		mrs	r6, cpsr	@ arch_local_irq_save
	cpsid	i
@ 0 "" 2
	.thumb
	.syntax unified
	ldr	r3, [r4, #336]
	cmp	r5, #0
	add	r3, r3, #1
	str	r3, [r4, #336]
	ble	.L259
	cbz	r3, .L259
	ldr	r2, .L267+8
	movs	r1, #4
	mov	r0, r5
	bl	mpi_queue_create
	movs	r3, #0
	str	r5, [r4, #392]
	str	r3, [r4, #400]
	str	r0, [r4, #352]
.L259:
	.syntax unified
@ 171 "./arch/arm/include/asm/irqflags.h" 1
		msr	cpsr_c, r6	@ local_irq_restore
@ 0 "" 2
	.thumb
	.syntax unified
	b	.L266
.L268:
	.align	2
.L267:
	.word	.LC10
	.word	.LANCHOR0+146
	.word	mpi_obj_unref
	.fnend
	.size	mpi_node_add_out_watcher, .-mpi_node_add_out_watcher
	.align	1
	.global	mpi_node_add_out_filter
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_node_add_out_filter, %function
mpi_node_add_out_filter:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r0, r1, r2, r3, r4, r5, r6, lr}
	.save {r4, r5, r6, lr}
	.pad #16
	mov	r4, r0
	mov	r5, r1
	cbz	r0, .L280
	ldr	r3, [r0, #12]
	and	r3, r3, #6
	cmp	r3, #2
	beq	.L271
.L280:
	add	sp, sp, #16
	@ sp needed
	pop	{r4, r5, r6, pc}
.L271:
	str	r1, [sp, #12]
	movs	r1, #5
	ldr	r3, [r0]
	ldr	r2, .L281
	str	r3, [sp, #8]
	ldr	r3, [r0, #44]
	movs	r0, #0
	ldr	r3, [r3, #44]
	str	r3, [sp, #4]
	movs	r3, #205
	str	r3, [sp]
	ldr	r3, .L281+4
	bl	vlog
	.syntax unified
@ 29 "./arch/arm/include/asm/irqflags.h" 1
		mrs	r6, cpsr	@ arch_local_irq_save
	cpsid	i
@ 0 "" 2
	.thumb
	.syntax unified
	ldr	r3, [r4, #340]
	cmp	r5, #0
	add	r3, r3, #1
	str	r3, [r4, #340]
	ble	.L273
	ldr	r3, [r4, #336]
	cbz	r3, .L273
	ldr	r2, .L281+8
	movs	r1, #4
	mov	r0, r5
	bl	mpi_queue_create
	movs	r3, #0
	str	r5, [r4, #392]
	str	r3, [r4, #400]
	str	r0, [r4, #352]
.L273:
	.syntax unified
@ 171 "./arch/arm/include/asm/irqflags.h" 1
		msr	cpsr_c, r6	@ local_irq_restore
@ 0 "" 2
	.thumb
	.syntax unified
	b	.L280
.L282:
	.align	2
.L281:
	.word	.LC11
	.word	.LANCHOR0+171
	.word	mpi_obj_unref
	.fnend
	.size	mpi_node_add_out_filter, .-mpi_node_add_out_filter
	.align	1
	.global	mpi_node_del_in_watcher
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_node_del_in_watcher, %function
mpi_node_del_in_watcher:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r0, r1, r2, r3, r4, lr}
	.save {r4, lr}
	.pad #16
	mov	r4, r0
	cbz	r0, .L294
	ldr	r3, [r0, #12]
	and	r3, r3, #6
	cmp	r3, #2
	beq	.L285
.L294:
	add	sp, sp, #16
	@ sp needed
	pop	{r4, pc}
.L285:
	ldr	r3, [r0]
	movs	r1, #5
	ldr	r2, .L295
	str	r3, [sp, #8]
	ldr	r3, [r0, #44]
	movs	r0, #0
	ldr	r3, [r3, #44]
	str	r3, [sp, #4]
	movs	r3, #206
	str	r3, [sp]
	ldr	r3, .L295+4
	bl	vlog
	ldr	r3, [r4, #324]
	cbz	r3, .L287
	subs	r3, r3, #1
	str	r3, [r4, #324]
.L287:
	movs	r1, #0
	mov	r0, r4
	bl	mpi_node_cleanup_in_buffer
	b	.L294
.L296:
	.align	2
.L295:
	.word	.LC12
	.word	.LANCHOR0+195
	.fnend
	.size	mpi_node_del_in_watcher, .-mpi_node_del_in_watcher
	.align	1
	.global	mpi_node_del_in_filter
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_node_del_in_filter, %function
mpi_node_del_in_filter:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r0, r1, r2, r3, r4, lr}
	.save {r4, lr}
	.pad #16
	mov	r4, r0
	cbz	r0, .L308
	ldr	r3, [r0, #12]
	and	r3, r3, #6
	cmp	r3, #2
	beq	.L299
.L308:
	add	sp, sp, #16
	@ sp needed
	pop	{r4, pc}
.L299:
	ldr	r3, [r0]
	movs	r1, #5
	ldr	r2, .L309
	str	r3, [sp, #8]
	ldr	r3, [r0, #44]
	movs	r0, #0
	ldr	r3, [r3, #44]
	str	r3, [sp, #4]
	movs	r3, #207
	str	r3, [sp]
	ldr	r3, .L309+4
	bl	vlog
	ldr	r3, [r4, #328]
	cbz	r3, .L301
	subs	r3, r3, #1
	str	r3, [r4, #328]
.L301:
	movs	r1, #0
	mov	r0, r4
	bl	mpi_node_cleanup_in_buffer
	b	.L308
.L310:
	.align	2
.L309:
	.word	.LC13
	.word	.LANCHOR0+219
	.fnend
	.size	mpi_node_del_in_filter, .-mpi_node_del_in_filter
	.align	1
	.global	mpi_node_del_out_watcher
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_node_del_out_watcher, %function
mpi_node_del_out_watcher:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r0, r1, r2, r3, r4, lr}
	.save {r4, lr}
	.pad #16
	mov	r4, r0
	cbz	r0, .L322
	ldr	r3, [r0, #12]
	and	r3, r3, #6
	cmp	r3, #2
	beq	.L313
.L322:
	add	sp, sp, #16
	@ sp needed
	pop	{r4, pc}
.L313:
	ldr	r3, [r0]
	movs	r1, #5
	ldr	r2, .L323
	str	r3, [sp, #8]
	ldr	r3, [r0, #44]
	movs	r0, #0
	ldr	r3, [r3, #44]
	str	r3, [sp, #4]
	movs	r3, #208
	str	r3, [sp]
	ldr	r3, .L323+4
	bl	vlog
	ldr	r3, [r4, #336]
	cbz	r3, .L315
	subs	r3, r3, #1
	str	r3, [r4, #336]
.L315:
	movs	r1, #0
	mov	r0, r4
	bl	mpi_node_cleanup_out_buffer
	b	.L322
.L324:
	.align	2
.L323:
	.word	.LC14
	.word	.LANCHOR0+242
	.fnend
	.size	mpi_node_del_out_watcher, .-mpi_node_del_out_watcher
	.align	1
	.global	mpi_node_del_out_filter
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_node_del_out_filter, %function
mpi_node_del_out_filter:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r0, r1, r2, r3, r4, lr}
	.save {r4, lr}
	.pad #16
	mov	r4, r0
	cbz	r0, .L336
	ldr	r3, [r0, #12]
	and	r3, r3, #6
	cmp	r3, #2
	beq	.L327
.L336:
	add	sp, sp, #16
	@ sp needed
	pop	{r4, pc}
.L327:
	ldr	r3, [r0]
	movs	r1, #5
	ldr	r2, .L337
	str	r3, [sp, #8]
	ldr	r3, [r0, #44]
	movs	r0, #0
	ldr	r3, [r3, #44]
	str	r3, [sp, #4]
	movs	r3, #209
	str	r3, [sp]
	ldr	r3, .L337+4
	bl	vlog
	ldr	r3, [r4, #340]
	cbz	r3, .L329
	subs	r3, r3, #1
	str	r3, [r4, #340]
.L329:
	movs	r1, #0
	mov	r0, r4
	bl	mpi_node_cleanup_out_buffer
	b	.L336
.L338:
	.align	2
.L337:
	.word	.LC15
	.word	.LANCHOR0+267
	.fnend
	.size	mpi_node_del_out_filter, .-mpi_node_del_out_filter
	.align	1
	.global	mpi_node_enable_auto_streamon
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_node_enable_auto_streamon, %function
mpi_node_enable_auto_streamon:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	@ link register save eliminated.
	ldr	r3, [r0, #12]
	cbz	r1, .L340
	orr	r1, r3, #16384
	lsls	r3, r3, #18
	str	r1, [r0, #12]
	bpl	.L339
	b	mpi_node_streamon
.L340:
	bic	r3, r3, #16384
	str	r3, [r0, #12]
.L339:
	bx	lr
	.fnend
	.size	mpi_node_enable_auto_streamon, .-mpi_node_enable_auto_streamon
	.align	1
	.global	mpi_dev_request_job
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_dev_request_job, %function
mpi_dev_request_job:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r0, r1, r2, r4, r5, lr}
	.save {r4, r5, lr}
	.pad #12
	mov	r4, r0
	ldr	r3, [r0, #44]
	movs	r1, #5
	ldr	r2, .L356
	movs	r0, #0
	str	r3, [sp, #4]
	movw	r3, #1084
	str	r3, [sp]
	ldr	r3, .L356+4
	bl	vlog
	cbz	r4, .L346
	ldr	r3, [r4, #12]
	and	r3, r3, #6
	cmp	r3, #2
	beq	.L347
.L346:
	movs	r5, #0
.L345:
	mov	r0, r5
	add	sp, sp, #12
	@ sp needed
	pop	{r4, r5, pc}
.L347:
	ldr	r0, [r4, #84]
	bl	mpi_job_pool_request_job
	mov	r5, r0
	cbz	r0, .L349
	mov	r0, r4
	bl	mpi_obj_ref
	str	r4, [r5, #44]
.L349:
	b	.L345
.L357:
	.align	2
.L356:
	.word	.LC16
	.word	.LANCHOR0+291
	.fnend
	.size	mpi_dev_request_job, .-mpi_dev_request_job
	.align	1
	.global	mpi_dev_request_job_for_node
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_dev_request_job_for_node, %function
mpi_dev_request_job_for_node:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r4, r5, lr}
	.save {r4, r5, lr}
	.pad #20
	sub	sp, sp, #20
	ldr	r3, [r1]
	mov	r5, r0
	mov	r4, r1
	ldr	r2, .L369
	movs	r1, #5
	str	r3, [sp, #8]
	ldr	r3, [r0, #44]
	movs	r0, #0
	str	r3, [sp, #4]
	movw	r3, #1110
	str	r3, [sp]
	ldr	r3, .L369+4
	bl	vlog
	cbz	r4, .L359
	ldr	r3, [r4, #12]
	and	r3, r3, #6
	cmp	r3, #2
	beq	.L360
.L359:
	movs	r5, #0
.L358:
	mov	r0, r5
	add	sp, sp, #20
	@ sp needed
	pop	{r4, r5, pc}
.L360:
	mov	r0, r5
	bl	mpi_dev_request_job
	mov	r5, r0
	cbz	r0, .L362
	mov	r0, r4
	bl	mpi_obj_ref
	str	r4, [r5, #48]
.L362:
	b	.L358
.L370:
	.align	2
.L369:
	.word	.LC17
	.word	.LANCHOR0+311
	.fnend
	.size	mpi_dev_request_job_for_node, .-mpi_dev_request_job_for_node
	.align	1
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	atomic_add.constprop.24, %function
atomic_add.constprop.24:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	@ link register save eliminated.
	pld	[r0]
	.syntax unified
@ 223 "./arch/arm/include/asm/atomic.h" 1
	@ atomic_add
1:	ldrex	r3, [r0]
	add	r3, r3, #1
	strex	r2, r3, [r0]
	teq	r2, #0
	bne	1b
@ 0 "" 2
	.thumb
	.syntax unified
	bx	lr
	.fnend
	.size	atomic_add.constprop.24, .-atomic_add.constprop.24
	.align	1
	.global	mpi_node_destroy
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_node_destroy, %function
mpi_node_destroy:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r4, r5, r6, r7, lr}
	.save {r4, r5, r6, r7, lr}
	.pad #20
	sub	sp, sp, #20
	ldr	r3, [r0]
	mov	r4, r0
	ldr	r2, .L415
	movs	r1, #5
	str	r3, [sp, #8]
	ldr	r3, [r0, #44]
	movs	r0, #0
	ldr	r3, [r3, #44]
	str	r3, [sp, #4]
	movw	r3, #937
	str	r3, [sp]
	ldr	r3, .L415+4
	bl	vlog
	.syntax unified
@ 29 "./arch/arm/include/asm/irqflags.h" 1
		mrs	r1, cpsr	@ arch_local_irq_save
	cpsid	i
@ 0 "" 2
	.thumb
	.syntax unified
	ldrd	r2, r3, [r4, #48]
	str	r3, [r2, #4]
	str	r2, [r3]
	mov	r2, #256
	mov	r3, #290
	strd	r2, r3, [r4, #48]
	.syntax unified
@ 171 "./arch/arm/include/asm/irqflags.h" 1
		msr	cpsr_c, r1	@ local_irq_restore
@ 0 "" 2
	.thumb
	.syntax unified
	ldr	r3, [r4, #12]
	movs	r1, #1
	mov	r0, r4
	orr	r3, r3, #1024
	str	r3, [r4, #12]
	bl	mpi_node_flush
	cbz	r4, .L373
	mov	r0, r4
	bl	mpi_obj_ref
.L373:
	ldr	r3, [r4, #12]
	bic	r3, r3, #2
	str	r3, [r4, #12]
	bl	synchronize_rcu
	ldr	r0, [r4, #60]
	cbz	r0, .L374
	mov	r1, r4
	bl	mpi_buf_pool_del_user
.L374:
	add	r6, r4, #292
.L375:
	mov	r0, r6
	bl	mpi_list_pop_obj_rcu
	mov	r5, r0
	cmp	r0, #0
	bne	.L376
	add	r6, r4, #300
.L377:
	mov	r0, r6
	bl	mpi_list_pop_obj_rcu
	mov	r5, r0
	cmp	r0, #0
	bne	.L378
	ldr	r0, [r4, #308]
	cbz	r0, .L379
	mov	r1, r5
	bl	mpi_queue_destroy
.L379:
	.syntax unified
@ 29 "./arch/arm/include/asm/irqflags.h" 1
		mrs	r3, cpsr	@ arch_local_irq_save
	cpsid	i
@ 0 "" 2
	.thumb
	.syntax unified
	ldr	r0, [r4, #288]
	cbz	r0, .L380
	movs	r2, #0
	str	r2, [r4, #288]
.L380:
	.syntax unified
@ 171 "./arch/arm/include/asm/irqflags.h" 1
		msr	cpsr_c, r3	@ local_irq_restore
@ 0 "" 2
	.thumb
	.syntax unified
	cbz	r0, .L381
	ldr	r3, [r4, #44]
	ldr	r3, [r3, #76]
	cbz	r3, .L381
	blx	r3
.L381:
	ldr	r3, [r4, #120]
	cbz	r3, .L382
	mov	r0, r4
	blx	r3
.L382:
	ldr	r3, [r4, #76]
	cmp	r3, #0
	bge	.L383
.L388:
	ldr	r5, [r4, #24]
	adds	r6, r5, #4
	add	r7, r5, #8
	mov	r0, r5
	bl	atomic_add.constprop.24
	mov	r0, r6
	bl	atomic_add.constprop.24
	ldr	r3, [r4, #16]
	cbnz	r3, .L385
	mov	r0, r7
	bl	complete_all
.L385:
	mov	r0, r4
	pld	[r6]
	bl	mpi_obj_unref
	mov	r0, r7
	bl	wait_for_completion
	.syntax unified
@ 224 "./arch/arm/include/asm/atomic.h" 1
	@ atomic_sub
1:	ldrex	r3, [r6]
	sub	r3, r3, #1
	strex	r2, r3, [r6]
	teq	r2, #0
	bne	1b
@ 0 "" 2
	.thumb
	.syntax unified
	pld	[r5]
	.syntax unified
@ 224 "./arch/arm/include/asm/atomic.h" 1
	@ atomic_sub_return
1:	ldrex	r3, [r5]
	sub	r3, r3, #1
	strex	r2, r3, [r5]
	teq	r2, #0
	bne	1b
@ 0 "" 2
	.thumb
	.syntax unified
	cbnz	r3, .L389
	mov	r0, r5
	bl	kfree
.L389:
	movs	r1, #1
	mov	r0, r4
	bl	mpi_node_cleanup_in_buffer
	mov	r0, r4
	movs	r1, #1
	bl	mpi_node_cleanup_out_buffer
	ldr	r0, [r4, #80]
	cbz	r0, .L390
	bl	kfree
.L390:
	mov	r0, r4
	add	sp, sp, #20
	@ sp needed
	pop	{r4, r5, r6, r7, lr}
	b	mpi_obj_unregister
.L376:
	mov	r1, r4
	bl	mpi_node_unbind
	mov	r0, r5
	bl	mpi_obj_unref
	b	.L375
.L378:
	mov	r0, r4
	mov	r1, r5
	bl	mpi_node_unbind
	mov	r0, r5
	bl	mpi_obj_unref
	b	.L377
.L383:
	ldr	r2, .L415+8
	mov	r0, #-1
	ldr	r3, [r2]
	subs	r3, r3, #36
.L386:
	add	r1, r3, #36
	cmp	r1, r2
	beq	.L388
	ldr	r1, [r4, #76]
	add	r1, r3, r1, lsl #2
	str	r0, [r1, #452]
	ldr	r1, [r4, #76]
	add	r1, r3, r1, lsl #2
	str	r0, [r1, #516]
	ldr	r3, [r3, #36]
	subs	r3, r3, #36
	b	.L386
.L416:
	.align	2
.L415:
	.word	.LC18
	.word	.LANCHOR0+340
	.word	mpi_buf_list
	.fnend
	.size	mpi_node_destroy, .-mpi_node_destroy
	.align	1
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	count_frame_rate.constprop.25, %function
count_frame_rate.constprop.25:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	ldr	r1, .L419
	ldr	r2, [r0, #188]
	ldr	r3, [r0, #184]
	push	{r4, lr}
	.save {r4, lr}
	adds	r3, r3, #1
	str	r3, [r0, #184]
	adds	r3, r2, #1
	str	r3, [r0, #188]
	ldr	r3, [r1]
	ldr	r4, [r0, #200]
	rsb	r3, r3, #100
	cmn	r3, r4
	itttt	mi
	ldrmi	r3, [r1]
	strdmi	r2, r3, [r0, #196]
	movmi	r3, #0
	strmi	r3, [r0, #188]
	pop	{r4, pc}
.L420:
	.align	2
.L419:
	.word	jiffies
	.fnend
	.size	count_frame_rate.constprop.25, .-count_frame_rate.constprop.25
	.align	1
	.global	mpi_dev_create_node_with_params
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_dev_create_node_with_params, %function
mpi_dev_create_node_with_params:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r0, r1, r2, r3, r4, r5, r6, r7, r8, r9, r10, lr}
	.save {r4, r5, r6, r7, r8, r9, r10, lr}
	.pad #16
	mov	r5, r0
	mov	r10, r1
	mov	r9, r2
	mov	r8, r3
	cbz	r0, .L422
	ldr	r7, [r0, #12]
	and	r7, r7, #6
	cmp	r7, #2
	beq	.L423
.L422:
	movs	r4, #0
.L421:
	mov	r0, r4
	add	sp, sp, #16
	@ sp needed
	pop	{r4, r5, r6, r7, r8, r9, r10, pc}
.L423:
	bl	mpi_obj_ref
	ldr	r6, .L445
	mov	r1, #3520
	ldr	r0, [r6, #36]
	bl	kmem_cache_alloc
	mov	r4, r0
	cbz	r0, .L425
	mov	r3, #-1
	str	r3, [r0, #76]
	movs	r3, #0
	strd	r3, r3, [r0, #124]
	strd	r3, r3, [r0, #132]
	strd	r3, r3, [r0, #184]
	strd	r3, r3, [r0, #192]
	ldr	r3, .L445+4
	str	r5, [r0, #44]
	str	r10, [r0, #56]
	ldr	r3, [r3]
	str	r3, [r0, #200]
	str	r3, [r0, #140]
	ldr	r3, .L445+8
	strd	r3, r3, [r0, #380]
	add	r3, r0, #292
	str	r3, [r0, #292]
	str	r3, [r0, #296]
	add	r3, r0, #300
	str	r3, [r0, #300]
	str	r3, [r0, #304]
	cmp	r9, #0
	beq	.L426
	mov	r1, r7
	ldr	r2, .L445+12
	mov	r0, r9
	bl	mpi_queue_create
	mov	r7, r0
	str	r0, [r4, #308]
	cbnz	r0, .L426
	mov	r0, r4
	mov	r4, r7
	bl	kfree
.L425:
	mov	r0, r5
	bl	mpi_obj_unref
	b	.L421
.L426:
	ldr	r0, [r6, #4]
	mov	r1, #3520
	bl	kmem_cache_alloc
	mov	r6, r0
	str	r0, [r4, #80]
	cbnz	r0, .L427
	mov	r0, r4
	mov	r4, r6
	bl	kfree
	b	.L425
.L427:
	add	r0, r4, #312
	bl	__init_completion
	add	r0, r4, #356
	bl	__init_completion
	add	r0, r4, #368
	bl	__init_completion
	movs	r3, #0
	movs	r2, #96
	movs	r1, #1
	mov	r0, r4
	bl	mpi_obj_register
	.syntax unified
@ 29 "./arch/arm/include/asm/irqflags.h" 1
		mrs	r1, cpsr	@ arch_local_irq_save
	cpsid	i
@ 0 "" 2
	.thumb
	.syntax unified
	ldr	r2, [r5, #92]
	add	r3, r4, #48
	add	r0, r5, #88
	str	r3, [r5, #92]
	strd	r0, r2, [r4, #48]
	str	r3, [r2]
	.syntax unified
@ 171 "./arch/arm/include/asm/irqflags.h" 1
		msr	cpsr_c, r1	@ local_irq_restore
@ 0 "" 2
	.thumb
	.syntax unified
	cmp	r8, #0
	beq	.L428
	mov	r1, r8
	mov	r0, r4
	bl	mpi_node_set_params
.L428:
	ldr	r3, [r5, #68]
	cbz	r3, .L429
	mov	r0, r4
	blx	r3
	str	r0, [r4, #288]
.L429:
	ldr	r3, [r4]
	movs	r1, #5
	ldr	r2, .L445+16
	movs	r0, #0
	str	r3, [sp, #8]
	ldr	r3, [r5, #44]
	str	r3, [sp, #4]
	movw	r3, #1066
	str	r3, [sp]
	ldr	r3, .L445+20
	bl	vlog
	b	.L425
.L446:
	.align	2
.L445:
	.word	kmalloc_caches
	.word	jiffies
	.word	500000
	.word	_mpi_job_discard
	.word	.LC19
	.word	.LANCHOR0+357
	.fnend
	.size	mpi_dev_create_node_with_params, .-mpi_dev_create_node_with_params
	.align	1
	.global	mpi_dev_unregister
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_dev_unregister, %function
mpi_dev_unregister:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r0, r1, r2, r4, r5, r6, r7, lr}
	.save {r4, r5, r6, r7, lr}
	.pad #12
	mov	r5, r0
	ldr	r3, [r0, #44]
	movs	r1, #5
	ldr	r2, .L456
	movs	r0, #0
	str	r3, [sp, #4]
	movw	r3, #1201
	str	r3, [sp]
	ldr	r3, .L456+4
	bl	vlog
	cbz	r5, .L448
	mov	r0, r5
	bl	mpi_obj_ref
.L448:
	ldr	r3, [r5, #12]
	mov	r6, r5
	bic	r3, r3, #2
	str	r3, [r5, #12]
	bl	synchronize_rcu
	ldr	r0, [r6, #88]!
	ldr	r4, [r0], #-48
	subs	r4, r4, #48
.L449:
	add	r3, r0, #48
	cmp	r3, r6
	bne	.L450
	ldr	r0, [r5, #84]
	bl	mpi_job_pool_destroy
	ldr	r4, [r5, #24]
	ldr	r3, [r5, #12]
	adds	r6, r4, #4
	add	r7, r4, #8
	orr	r3, r3, #4
	mov	r0, r4
	str	r3, [r5, #12]
	bl	atomic_add.constprop.24
	mov	r0, r6
	bl	atomic_add.constprop.24
	ldr	r3, [r5, #16]
	cbnz	r3, .L451
	mov	r0, r7
	bl	complete_all
.L451:
	mov	r0, r5
	pld	[r6]
	bl	mpi_obj_unref
	mov	r0, r7
	bl	wait_for_completion
	.syntax unified
@ 224 "./arch/arm/include/asm/atomic.h" 1
	@ atomic_sub
1:	ldrex	r3, [r6]
	sub	r3, r3, #1
	strex	r2, r3, [r6]
	teq	r2, #0
	bne	1b
@ 0 "" 2
	.thumb
	.syntax unified
	pld	[r4]
	.syntax unified
@ 224 "./arch/arm/include/asm/atomic.h" 1
	@ atomic_sub_return
1:	ldrex	r3, [r4]
	sub	r3, r3, #1
	strex	r2, r3, [r4]
	teq	r2, #0
	bne	1b
@ 0 "" 2
	.thumb
	.syntax unified
	cbnz	r3, .L452
	mov	r0, r4
	bl	kfree
.L452:
	ldr	r0, [r5, #44]
	bl	kfree
	mov	r0, r5
	bl	mpi_obj_unregister
	movs	r0, #0
	add	sp, sp, #12
	@ sp needed
	pop	{r4, r5, r6, r7, pc}
.L450:
	bl	mpi_node_destroy
	ldr	r3, [r4, #48]
	mov	r0, r4
	sub	r4, r3, #48
	b	.L449
.L457:
	.align	2
.L456:
	.word	.LC20
	.word	.LANCHOR0+389
	.fnend
	.size	mpi_dev_unregister, .-mpi_dev_unregister
	.align	1
	.global	add_user_to_buf
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	add_user_to_buf, %function
add_user_to_buf:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r4, r5, lr}
	.save {r4, r5, lr}
	cbz	r1, .L458
	ldr	r3, [r0, #76]
	adds	r3, r3, #1
	bne	.L461
	.syntax unified
@ 29 "./arch/arm/include/asm/irqflags.h" 1
		mrs	r4, cpsr	@ arch_local_irq_save
	cpsid	i
@ 0 "" 2
	.thumb
	.syntax unified
	movs	r3, #0
.L472:
	str	r3, [r0, #76]
	ldr	r3, [r0, #76]
	cmp	r3, #15
	ble	.L464
.L463:
	.syntax unified
@ 171 "./arch/arm/include/asm/irqflags.h" 1
		msr	cpsr_c, r4	@ local_irq_restore
@ 0 "" 2
	.thumb
	.syntax unified
.L461:
	ldr	r3, [r0, #76]
	cmp	r3, #15
	itt	gt
	mvngt	r3, #1
	strgt	r3, [r0, #76]
	ldr	r3, [r0, #76]
	cmp	r3, #0
	blt	.L458
	cmp	r2, #0
	ite	ne
	movne	r2, #16
	moveq	r2, #0
	add	r3, r3, r2
	add	r1, r1, r3, lsl #2
	str	r0, [r1, #452]
.L458:
	pop	{r4, r5, pc}
.L464:
	add	r5, r1, r3, lsl #2
	ldr	r5, [r5, #452]
	adds	r5, r5, #1
	beq	.L463
	adds	r3, r3, #1
	b	.L472
	.fnend
	.size	add_user_to_buf, .-add_user_to_buf
	.align	1
	.global	mpi_node_buffer_in
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_node_buffer_in, %function
mpi_node_buffer_in:
	.fnstart
	@ args = 0, pretend = 0, frame = 32
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r4, r5, r6, r7, lr}
	.save {r4, r5, r6, r7, lr}
	mov	r4, r0
	.pad #60
	sub	sp, sp, #60
	mov	r5, r1
	mov	r6, r2
	cbz	r0, .L474
	ldr	r3, [r0, #12]
	and	r3, r3, #6
	cmp	r3, #2
	beq	.L475
.L474:
.L473:
	add	sp, sp, #60
	@ sp needed
	pop	{r4, r5, r6, r7, pc}
.L475:
	adds	r0, r0, #248
	bl	ktime_get_ts64
	mov	r0, r4
	bl	mpi_obj_ref
	ldr	r3, [r4, #12]
	lsls	r3, r3, #19
	bpl	.L477
	ldr	r3, [r4, #44]
	ldr	r0, [r5]
	ldr	r1, [r4]
	ldr	r2, [r3, #44]
	ldr	r7, .L519
	ldr	r3, .L519+4
	strd	r2, r1, [sp, #4]
	movs	r1, #5
	cmp	r6, #0
	it	eq
	moveq	r3, r7
	ldr	r2, .L519+8
	strd	r0, r3, [sp, #12]
	movw	r3, #481
	movs	r0, #0
	str	r3, [sp]
	ldr	r3, .L519+12
	bl	vlog
	ldr	r1, [r4, #144]
	cmp	r1, #0
	beq	.L479
	ldr	r3, [r4, #148]
	cmp	r3, #0
	ble	.L480
	subs	r3, r3, #1
	str	r3, [r4, #148]
.L481:
	movs	r1, #0
.L518:
	mov	r0, r4
	bl	count_frame_rate.part.1
.L477:
	add	r0, sp, #24
	bl	ktime_get_ts64
	ldr	r1, [r4, #256]
	ldrd	r2, r3, [r4, #248]
	ldr	r0, [sp, #32]
	ldr	r5, [sp, #24]
	subs	r0, r0, r1
	subs	r2, r5, r2
	asr	r1, r0, #31
	strd	r0, [sp]
	ldr	r1, [sp, #28]
	add	r0, sp, #40
	sbc	r3, r1, r3
	bl	set_normalized_timespec64
	ldr	r0, .L519+16
	ldr	r3, [sp, #48]
	ldr	r2, [sp, #40]
	smull	r0, r1, r3, r0
	asrs	r3, r3, #31
	mov	r0, r4
	rsb	r3, r3, r1, asr #6
	ldr	r1, .L519+20
	mla	r3, r1, r2, r3
	str	r3, [r4, #280]
	bl	mpi_obj_unref
	b	.L473
.L480:
	ldr	r0, [r4, #124]
	bl	__aeabi_idivmod
	add	r1, r1, r4
	ldrb	r3, [r1, #152]	@ zero_extendqisi2
	cmp	r3, #0
	bne	.L481
.L479:
	cmp	r6, #0
	bne	.L483
	ldr	r3, [r4, #324]
	cbnz	r3, .L484
	ldr	r3, [r4, #328]
	cmp	r3, #0
	beq	.L483
.L484:
	.syntax unified
@ 29 "./arch/arm/include/asm/irqflags.h" 1
		mrs	r6, cpsr	@ arch_local_irq_save
	cpsid	i
@ 0 "" 2
	.thumb
	.syntax unified
	ldr	r3, [r4, #324]
	cbz	r3, .L485
	cbz	r5, .L486
	mov	r0, r5
	bl	mpi_obj_ref
.L486:
	ldr	r2, [r4, #396]
	ldr	r3, [r4, #388]
	ldr	r0, [r4, #348]
	cmp	r2, r3
	bcs	.L487
	mov	r1, r5
	bl	mpi_queue_push_obj
	cbz	r0, .L488
	ldr	r3, [r4, #396]
	adds	r3, r3, #1
	str	r3, [r4, #396]
.L489:
	add	r0, r4, #356
	bl	complete_all
	.syntax unified
@ 171 "./arch/arm/include/asm/irqflags.h" 1
		msr	cpsr_c, r6	@ local_irq_restore
@ 0 "" 2
	.thumb
	.syntax unified
.L485:
	ldr	r3, [r4, #328]
	cbz	r3, .L483
	ldr	r3, [r4, #332]
	cmp	r3, #0
	beq	.L481
	mov	r1, r5
	mov	r0, r4
	blx	r3
	b	.L481
.L488:
	movw	r3, #493
.L516:
	str	r3, [sp]
	movs	r1, #2
	ldr	r3, .L519+12
	ldr	r2, .L519+24
	bl	vlog
	b	.L517
.L487:
	bl	mpi_queue_pop_obj
	cbnz	r0, .L490
.L517:
	mov	r0, r5
	bl	mpi_obj_unref
	b	.L489
.L490:
	bl	mpi_obj_unref
	mov	r1, r5
	ldr	r0, [r4, #348]
	bl	mpi_queue_push_obj
	cmp	r0, #0
	bne	.L489
	mov	r3, #504
	b	.L516
.L483:
	movs	r2, #0
	mov	r1, r5
	mov	r0, r4
	bl	add_user_to_buf
	ldr	r3, [r4, #44]
	movs	r1, #1
	mov	r2, r5
	ldr	r3, [r3, #80]
	blx	r3
	mov	r1, r0
	b	.L518
.L520:
	.align	2
.L519:
	.word	.LC22
	.word	.LC21
	.word	.LC23
	.word	.LANCHOR0+408
	.word	274877907
	.word	1000000
	.word	.LC24
	.fnend
	.size	mpi_node_buffer_in, .-mpi_node_buffer_in
	.align	1
	.global	mpi_node_get_in_buffer
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_node_get_in_buffer, %function
mpi_node_get_in_buffer:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r4, r5, r6, r7, lr}
	.save {r4, r5, r6, r7, lr}
	mov	r4, r0
	.pad #28
	sub	sp, sp, #28
	mov	r6, r1
	cbz	r0, .L522
	ldr	r3, [r0, #12]
	and	r3, r3, #6
	cmp	r3, #2
	beq	.L523
.L522:
	movs	r5, #0
.L521:
	mov	r0, r5
	add	sp, sp, #28
	@ sp needed
	pop	{r4, r5, r6, r7, pc}
.L523:
	bl	mpi_obj_ref
	cbz	r6, .L525
.L532:
	.syntax unified
@ 29 "./arch/arm/include/asm/irqflags.h" 1
		mrs	r2, cpsr	@ arch_local_irq_save
	cpsid	i
@ 0 "" 2
	.thumb
	.syntax unified
	ldr	r5, [r4, #12]
	add	r0, r4, #356
	ldr	r3, .L541
	ands	r5, r5, #4096
	bne	.L526
	.syntax unified
@ 171 "./arch/arm/include/asm/irqflags.h" 1
		msr	cpsr_c, r2	@ local_irq_restore
@ 0 "" 2
	.thumb
	.syntax unified
	ldr	r2, [r4, #380]
	str	r5, [r4, #356]
	umull	r2, r3, r2, r3
	lsrs	r1, r3, #3
	bl	wait_for_completion_interruptible_timeout
.L527:
	mov	r0, r4
	bl	mpi_obj_unref
	b	.L521
.L526:
	movs	r1, #0
	str	r1, [r4, #356]
	.syntax unified
@ 171 "./arch/arm/include/asm/irqflags.h" 1
		msr	cpsr_c, r2	@ local_irq_restore
@ 0 "" 2
	.thumb
	.syntax unified
	ldr	r2, [r4, #380]
	movs	r6, #1
	umull	r2, r3, r2, r3
	lsrs	r1, r3, #3
	bl	wait_for_completion_interruptible_timeout
.L525:
	.syntax unified
@ 29 "./arch/arm/include/asm/irqflags.h" 1
		mrs	r7, cpsr	@ arch_local_irq_save
	cpsid	i
@ 0 "" 2
	.thumb
	.syntax unified
	ldr	r3, [r4, #324]
	cbnz	r3, .L528
.L531:
	movs	r5, #0
.L529:
	.syntax unified
@ 171 "./arch/arm/include/asm/irqflags.h" 1
		msr	cpsr_c, r7	@ local_irq_restore
@ 0 "" 2
	.thumb
	.syntax unified
	movs	r2, #1
	mov	r1, r5
	mov	r0, r4
	bl	add_user_to_buf
	b	.L527
.L528:
	ldr	r0, [r4, #348]
	bl	mpi_queue_pop_obj
	mov	r5, r0
	cbnz	r0, .L530
	cmp	r6, #0
	bne	.L531
	.syntax unified
@ 171 "./arch/arm/include/asm/irqflags.h" 1
		msr	cpsr_c, r7	@ local_irq_restore
@ 0 "" 2
	.thumb
	.syntax unified
	b	.L532
.L530:
	ldr	r3, [r4, #44]
	ldr	r0, .L541+4
	ldr	r1, .L541+8
	ldr	r3, [r3, #44]
	cmp	r6, #0
	it	eq
	moveq	r1, r0
	ldr	r2, [r4]
	ldr	r0, [r5]
	strd	r3, r2, [sp, #4]
	movw	r3, #642
	strd	r1, r0, [sp, #12]
	movs	r1, #5
	str	r3, [sp]
	movs	r0, #0
	ldr	r3, .L541+12
	ldr	r2, .L541+16
	bl	vlog
	b	.L529
.L542:
	.align	2
.L541:
	.word	-858993459
	.word	.LC26
	.word	.LC25
	.word	.LANCHOR0+427
	.word	.LC27
	.fnend
	.size	mpi_node_get_in_buffer, .-mpi_node_get_in_buffer
	.align	1
	.global	mpi_node_pick_in_buffer
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_node_pick_in_buffer, %function
mpi_node_pick_in_buffer:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r3, r4, r5, lr}
	.save {r3, r4, r5, lr}
	movs	r1, #1
	mov	r4, r0
	bl	mpi_node_add_in_watcher
	movs	r1, #1
	mov	r0, r4
	bl	mpi_node_get_in_buffer
	mov	r5, r0
	mov	r0, r4
	bl	mpi_node_del_in_watcher
	mov	r0, r5
	pop	{r3, r4, r5, pc}
	.fnend
	.size	mpi_node_pick_in_buffer, .-mpi_node_pick_in_buffer
	.align	1
	.global	mpi_node_get_out_buffer
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_node_get_out_buffer, %function
mpi_node_get_out_buffer:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r4, r5, r6, r7, lr}
	.save {r4, r5, r6, r7, lr}
	mov	r4, r0
	.pad #28
	sub	sp, sp, #28
	mov	r6, r1
	cbz	r0, .L545
	ldr	r3, [r0, #12]
	and	r3, r3, #6
	cmp	r3, #2
	beq	.L546
.L545:
	movs	r5, #0
.L544:
	mov	r0, r5
	add	sp, sp, #28
	@ sp needed
	pop	{r4, r5, r6, r7, pc}
.L546:
	bl	mpi_obj_ref
	cbz	r6, .L548
.L555:
	.syntax unified
@ 29 "./arch/arm/include/asm/irqflags.h" 1
		mrs	r2, cpsr	@ arch_local_irq_save
	cpsid	i
@ 0 "" 2
	.thumb
	.syntax unified
	ldr	r5, [r4, #12]
	add	r0, r4, #368
	ldr	r3, .L564
	ands	r5, r5, #4096
	bne	.L549
	.syntax unified
@ 171 "./arch/arm/include/asm/irqflags.h" 1
		msr	cpsr_c, r2	@ local_irq_restore
@ 0 "" 2
	.thumb
	.syntax unified
	ldr	r2, [r4, #384]
	str	r5, [r4, #368]
	umull	r2, r3, r2, r3
	lsrs	r1, r3, #3
	bl	wait_for_completion_interruptible_timeout
.L550:
	mov	r0, r4
	bl	mpi_obj_unref
	b	.L544
.L549:
	movs	r1, #0
	str	r1, [r4, #368]
	.syntax unified
@ 171 "./arch/arm/include/asm/irqflags.h" 1
		msr	cpsr_c, r2	@ local_irq_restore
@ 0 "" 2
	.thumb
	.syntax unified
	ldr	r2, [r4, #384]
	movs	r6, #1
	umull	r2, r3, r2, r3
	lsrs	r1, r3, #3
	bl	wait_for_completion_interruptible_timeout
.L548:
	.syntax unified
@ 29 "./arch/arm/include/asm/irqflags.h" 1
		mrs	r7, cpsr	@ arch_local_irq_save
	cpsid	i
@ 0 "" 2
	.thumb
	.syntax unified
	ldr	r3, [r4, #336]
	cbnz	r3, .L551
.L554:
	movs	r5, #0
.L552:
	.syntax unified
@ 171 "./arch/arm/include/asm/irqflags.h" 1
		msr	cpsr_c, r7	@ local_irq_restore
@ 0 "" 2
	.thumb
	.syntax unified
	movs	r2, #1
	mov	r1, r5
	mov	r0, r4
	bl	add_user_to_buf
	b	.L550
.L551:
	ldr	r0, [r4, #352]
	bl	mpi_queue_pop_obj
	mov	r5, r0
	cbnz	r0, .L553
	cmp	r6, #0
	bne	.L554
	.syntax unified
@ 171 "./arch/arm/include/asm/irqflags.h" 1
		msr	cpsr_c, r7	@ local_irq_restore
@ 0 "" 2
	.thumb
	.syntax unified
	b	.L555
.L553:
	ldr	r3, [r4, #44]
	ldr	r0, .L564+4
	ldr	r1, .L564+8
	ldr	r3, [r3, #44]
	cmp	r6, #0
	it	eq
	moveq	r1, r0
	ldr	r2, [r4]
	ldr	r0, [r5]
	strd	r3, r2, [sp, #4]
	movw	r3, #695
	strd	r1, r0, [sp, #12]
	movs	r1, #5
	str	r3, [sp]
	movs	r0, #0
	ldr	r3, .L564+12
	ldr	r2, .L564+16
	bl	vlog
	b	.L552
.L565:
	.align	2
.L564:
	.word	-858993459
	.word	.LC22
	.word	.LC25
	.word	.LANCHOR0+450
	.word	.LC28
	.fnend
	.size	mpi_node_get_out_buffer, .-mpi_node_get_out_buffer
	.align	1
	.global	mpi_node_pick_out_buffer
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_node_pick_out_buffer, %function
mpi_node_pick_out_buffer:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r3, r4, r5, lr}
	.save {r3, r4, r5, lr}
	movs	r1, #1
	mov	r4, r0
	bl	mpi_node_add_out_watcher
	movs	r1, #1
	mov	r0, r4
	bl	mpi_node_get_out_buffer
	mov	r5, r0
	mov	r0, r4
	bl	mpi_node_del_out_watcher
	mov	r0, r5
	pop	{r3, r4, r5, pc}
	.fnend
	.size	mpi_node_pick_out_buffer, .-mpi_node_pick_out_buffer
	.align	1
	.global	mpi_node_request_buf
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_node_request_buf, %function
mpi_node_request_buf:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r4, r5, r6, lr}
	.save {r4, r5, r6, lr}
	mov	r4, r0
	.pad #24
	sub	sp, sp, #24
	mov	r5, r1
	ldr	r6, [r0, #60]
	cbz	r0, .L568
	ldr	r3, [r0, #12]
	and	r3, r3, #6
	cmp	r3, #2
	beq	.L569
.L568:
	movs	r5, #0
.L567:
	mov	r0, r5
	add	sp, sp, #24
	@ sp needed
	pop	{r4, r5, r6, pc}
.L569:
	ldr	r3, [r0, #44]
	ldr	r1, [r0]
	ldr	r2, [r3, #44]
	cbz	r5, .L573
	ldr	r3, [r5]
.L571:
	strd	r1, r3, [sp, #8]
	movs	r0, #0
	str	r2, [sp, #4]
	movw	r3, #721
	ldr	r2, .L580
	movs	r1, #5
	str	r3, [sp]
	ldr	r3, .L580+4
	bl	vlog
	mov	r1, r5
	mov	r0, r6
	bl	mpi_buf_pool_request_buf
	mov	r5, r0
	cbz	r0, .L572
	ldr	r3, [r6]
	movs	r1, #5
	ldr	r2, .L580+8
	str	r3, [sp, #16]
	ldr	r3, [r0]
	movs	r0, #0
	str	r3, [sp, #12]
	ldr	r3, [r4]
	str	r3, [sp, #8]
	ldr	r3, [r4, #44]
	ldr	r3, [r3, #44]
	str	r3, [sp, #4]
	movw	r3, #727
	str	r3, [sp]
	ldr	r3, .L580+4
	bl	vlog
	ldr	r3, [r6, #64]
	str	r3, [r4, #72]
.L572:
	movs	r2, #0
	mov	r1, r5
	mov	r0, r4
	bl	add_user_to_buf
	b	.L567
.L573:
	mov	r3, #-1
	b	.L571
.L581:
	.align	2
.L580:
	.word	.LC29
	.word	.LANCHOR0+474
	.word	.LC30
	.fnend
	.size	mpi_node_request_buf, .-mpi_node_request_buf
	.align	1
	.global	remove_user_from_buf
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	remove_user_from_buf, %function
remove_user_from_buf:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	@ link register save eliminated.
	cbz	r1, .L582
	cmp	r0, #0
	blt	.L582
	cmp	r2, #0
	mov	r2, #0
	ite	ne
	movne	r3, #16
	moveq	r3, #0
	add	r3, r3, r0
	adds	r3, r3, #112
	add	r3, r1, r3, lsl #2
	str	r2, [r3, #4]
.L582:
	bx	lr
	.fnend
	.size	remove_user_from_buf, .-remove_user_from_buf
	.align	1
	.global	mpi_node_release_buffer_flag
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_node_release_buffer_flag, %function
mpi_node_release_buffer_flag:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r3, r4, r5, r6, r7, lr}
	.save {r3, r4, r5, r6, r7, lr}
	mov	r4, r0
	mov	r6, r1
	mov	r5, r2
	cbz	r0, .L590
	ldr	r3, [r0, #12]
	and	r3, r3, #6
	cmp	r3, #2
	beq	.L591
.L590:
	pop	{r3, r4, r5, r6, r7, pc}
.L591:
	bl	mpi_obj_ref
	.syntax unified
@ 29 "./arch/arm/include/asm/irqflags.h" 1
		mrs	r7, cpsr	@ arch_local_irq_save
	cpsid	i
@ 0 "" 2
	.thumb
	.syntax unified
	movs	r2, #1
	ldr	r0, [r4, #76]
	mov	r1, r6
	bl	remove_user_from_buf
	mov	r0, r6
	bl	mpi_obj_unref
	cbz	r5, .L593
	ldr	r3, [r5]
	subs	r3, r3, #1
	str	r3, [r5]
.L593:
	.syntax unified
@ 171 "./arch/arm/include/asm/irqflags.h" 1
		msr	cpsr_c, r7	@ local_irq_restore
@ 0 "" 2
	.thumb
	.syntax unified
	mov	r0, r4
	pop	{r3, r4, r5, r6, r7, lr}
	b	mpi_obj_unref
	.fnend
	.size	mpi_node_release_buffer_flag, .-mpi_node_release_buffer_flag
	.align	1
	.global	mpi_node_buffer_out
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_node_buffer_out, %function
mpi_node_buffer_out:
	.fnstart
	@ args = 0, pretend = 0, frame = 32
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r4, r5, r6, r7, lr}
	.save {r4, r5, r6, r7, lr}
	mov	r4, r0
	.pad #60
	sub	sp, sp, #60
	mov	r5, r1
	mov	r6, r2
	cbz	r0, .L602
	ldr	r3, [r0, #12]
	and	r3, r3, #6
	cmp	r3, #2
	beq	.L603
.L602:
.L601:
	add	sp, sp, #60
	@ sp needed
	pop	{r4, r5, r6, r7, pc}
.L603:
	add	r0, r0, #264
	bl	ktime_get_ts64
	mov	r0, r4
	bl	mpi_obj_ref
	ldr	r3, [r4, #44]
	ldr	r0, [r5]
	ldr	r1, [r4]
	ldr	r2, [r3, #44]
	ldr	r7, .L645
	ldr	r3, .L645+4
	strd	r2, r1, [sp, #4]
	movs	r1, #5
	cmp	r6, #0
	it	eq
	moveq	r3, r7
	ldr	r2, .L645+8
	strd	r0, r3, [sp, #12]
	mov	r3, #548
	movs	r0, #0
	str	r3, [sp]
	ldr	r3, .L645+12
	bl	vlog
	ldr	r1, [r4, #204]
	cmp	r1, #0
	beq	.L606
	ldr	r3, [r4, #208]
	cmp	r3, #0
	ble	.L607
	subs	r3, r3, #1
	str	r3, [r4, #208]
.L608:
	mov	r0, r4
	bl	count_frame_rate.constprop.25
.L618:
	add	r0, sp, #24
	bl	ktime_get_ts64
	ldr	r1, [r4, #272]
	ldrd	r2, r3, [r4, #264]
	ldr	r0, [sp, #32]
	ldr	r5, [sp, #24]
	subs	r0, r0, r1
	subs	r2, r5, r2
	asr	r1, r0, #31
	strd	r0, [sp]
	ldr	r1, [sp, #28]
	add	r0, sp, #40
	sbc	r3, r1, r3
	bl	set_normalized_timespec64
	ldr	r0, .L645+16
	ldr	r3, [sp, #48]
	ldr	r2, [sp, #40]
	smull	r0, r1, r3, r0
	asrs	r3, r3, #31
	mov	r0, r4
	rsb	r3, r3, r1, asr #6
	ldr	r1, .L645+20
	mla	r3, r1, r2, r3
	str	r3, [r4, #284]
	bl	mpi_obj_unref
	b	.L601
.L607:
	ldr	r0, [r4, #184]
	bl	__aeabi_idivmod
	add	r1, r1, r4
	ldrb	r3, [r1, #212]	@ zero_extendqisi2
	cmp	r3, #0
	bne	.L608
.L606:
	cmp	r6, #0
	bne	.L610
	ldr	r3, [r4, #336]
	cbnz	r3, .L611
	ldr	r3, [r4, #340]
	cmp	r3, #0
	beq	.L610
.L611:
	.syntax unified
@ 29 "./arch/arm/include/asm/irqflags.h" 1
		mrs	r6, cpsr	@ arch_local_irq_save
	cpsid	i
@ 0 "" 2
	.thumb
	.syntax unified
	ldr	r3, [r4, #336]
	cbz	r3, .L612
	cbz	r5, .L613
	mov	r0, r5
	bl	mpi_obj_ref
.L613:
	ldr	r2, [r4, #400]
	ldr	r3, [r4, #392]
	ldr	r0, [r4, #352]
	cmp	r2, r3
	bcs	.L614
	mov	r1, r5
	bl	mpi_queue_push_obj
	cbz	r0, .L615
	ldr	r3, [r4, #400]
	adds	r3, r3, #1
	str	r3, [r4, #400]
.L616:
	add	r0, r4, #368
	bl	complete_all
	.syntax unified
@ 171 "./arch/arm/include/asm/irqflags.h" 1
		msr	cpsr_c, r6	@ local_irq_restore
@ 0 "" 2
	.thumb
	.syntax unified
.L612:
	ldr	r3, [r4, #340]
	cbz	r3, .L610
	ldr	r3, [r4, #344]
	cmp	r3, #0
	beq	.L608
	mov	r1, r5
	mov	r0, r4
	blx	r3
	b	.L608
.L615:
	movw	r3, #559
.L643:
	str	r3, [sp]
	movs	r1, #2
	ldr	r3, .L645+12
	ldr	r2, .L645+24
	bl	vlog
	b	.L644
.L614:
	bl	mpi_queue_pop_obj
	cbnz	r0, .L617
.L644:
	mov	r0, r5
	bl	mpi_obj_unref
	b	.L616
.L617:
	bl	mpi_obj_unref
	mov	r1, r5
	ldr	r0, [r4, #352]
	bl	mpi_queue_push_obj
	cmp	r0, #0
	bne	.L616
	movw	r3, #571
	b	.L643
.L610:
	movs	r2, #0
	mov	r1, r5
	ldr	r0, [r4, #76]
	add	r7, r4, #300
	bl	remove_user_from_buf
	mov	r0, r4
	bl	count_frame_rate.constprop.25
	ldr	r6, [r4, #300]
	subs	r6, r6, #4
.L619:
	adds	r3, r6, #4
	cmp	r3, r7
	beq	.L618
	ldr	r0, [r6]
	movs	r2, #0
	mov	r1, r5
	bl	mpi_node_buffer_in
	ldr	r6, [r6, #4]
	subs	r6, r6, #4
	b	.L619
.L646:
	.align	2
.L645:
	.word	.LC22
	.word	.LC21
	.word	.LC31
	.word	.LANCHOR0+495
	.word	274877907
	.word	1000000
	.word	.LC32
	.fnend
	.size	mpi_node_buffer_out, .-mpi_node_buffer_out
	.align	1
	.global	mpi_node_buffer_available
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_node_buffer_available, %function
mpi_node_buffer_available:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r0, r1, r2, r3, r4, r5, r6, lr}
	.save {r4, r5, r6, lr}
	.pad #16
	mov	r4, r0
	mov	r5, r1
	ldr	r6, [r0, #44]
	cbz	r0, .L648
	ldr	r3, [r0, #12]
	and	r3, r3, #6
	cmp	r3, #2
	beq	.L649
.L648:
	add	sp, sp, #16
	@ sp needed
	pop	{r4, r5, r6, pc}
.L649:
	bl	mpi_obj_ref
	ldr	r3, [r4, #12]
	lsls	r3, r3, #19
	bpl	.L652
	ldr	r3, [r4]
	movs	r1, #5
	ldr	r2, .L661
	movs	r0, #0
	str	r3, [sp, #12]
	ldr	r3, [r4, #44]
	ldr	r3, [r3, #44]
	str	r3, [sp, #8]
	ldr	r3, [r5]
	str	r3, [sp, #4]
	mov	r3, #454
	str	r3, [sp]
	ldr	r3, .L661+4
	bl	vlog
	ldr	r3, [r6, #80]
	cbz	r3, .L652
	mov	r2, r5
	movs	r1, #0
	mov	r0, r4
	blx	r3
.L652:
	mov	r0, r4
	add	sp, sp, #16
	@ sp needed
	pop	{r4, r5, r6, lr}
	b	mpi_obj_unref
.L662:
	.align	2
.L661:
	.word	.LC33
	.word	.LANCHOR0+515
	.fnend
	.size	mpi_node_buffer_available, .-mpi_node_buffer_available
	.section	.rodata
	.set	.LANCHOR0,. + 0
	.type	__func__.36625, %object
	.size	__func__.36625, 18
__func__.36625:
	.ascii	"mpi_node_streamon\000"
	.type	__func__.36640, %object
	.size	__func__.36640, 19
__func__.36640:
	.ascii	"mpi_node_streamoff\000"
	.type	__func__.36887, %object
	.size	__func__.36887, 15
__func__.36887:
	.ascii	"mpi_node_flush\000"
	.type	__func__.36915, %object
	.size	__func__.36915, 16
__func__.36915:
	.ascii	"mpi_node_unbind\000"
	.type	__func__.36941, %object
	.size	__func__.36941, 14
__func__.36941:
	.ascii	"mpi_node_bind\000"
	.type	__func__.37194, %object
	.size	__func__.37194, 17
__func__.37194:
	.ascii	"mpi_dev_register\000"
	.type	__func__.36388, %object
	.size	__func__.36388, 24
__func__.36388:
	.ascii	"mpi_node_add_in_watcher\000"
	.type	__func__.36402, %object
	.size	__func__.36402, 23
__func__.36402:
	.ascii	"mpi_node_add_in_filter\000"
	.type	__func__.36416, %object
	.size	__func__.36416, 25
__func__.36416:
	.ascii	"mpi_node_add_out_watcher\000"
	.type	__func__.36430, %object
	.size	__func__.36430, 24
__func__.36430:
	.ascii	"mpi_node_add_out_filter\000"
	.type	__func__.36442, %object
	.size	__func__.36442, 24
__func__.36442:
	.ascii	"mpi_node_del_in_watcher\000"
	.type	__func__.36450, %object
	.size	__func__.36450, 23
__func__.36450:
	.ascii	"mpi_node_del_in_filter\000"
	.type	__func__.36458, %object
	.size	__func__.36458, 25
__func__.36458:
	.ascii	"mpi_node_del_out_watcher\000"
	.type	__func__.36466, %object
	.size	__func__.36466, 24
__func__.36466:
	.ascii	"mpi_node_del_out_filter\000"
	.type	__func__.37056, %object
	.size	__func__.37056, 20
__func__.37056:
	.ascii	"mpi_dev_request_job\000"
	.type	__func__.37070, %object
	.size	__func__.37070, 29
__func__.37070:
	.ascii	"mpi_dev_request_job_for_node\000"
	.type	__func__.36970, %object
	.size	__func__.36970, 17
__func__.36970:
	.ascii	"mpi_node_destroy\000"
	.type	__func__.37043, %object
	.size	__func__.37043, 32
__func__.37043:
	.ascii	"mpi_dev_create_node_with_params\000"
	.type	__func__.37155, %object
	.size	__func__.37155, 19
__func__.37155:
	.ascii	"mpi_dev_unregister\000"
	.type	__func__.36687, %object
	.size	__func__.36687, 19
__func__.36687:
	.ascii	"mpi_node_buffer_in\000"
	.type	__func__.36817, %object
	.size	__func__.36817, 23
__func__.36817:
	.ascii	"mpi_node_get_in_buffer\000"
	.type	__func__.36854, %object
	.size	__func__.36854, 24
__func__.36854:
	.ascii	"mpi_node_get_out_buffer\000"
	.type	__func__.36868, %object
	.size	__func__.36868, 21
__func__.36868:
	.ascii	"mpi_node_request_buf\000"
	.type	__func__.36722, %object
	.size	__func__.36722, 20
__func__.36722:
	.ascii	"mpi_node_buffer_out\000"
	.type	__func__.36673, %object
	.size	__func__.36673, 26
__func__.36673:
	.ascii	"mpi_node_buffer_available\000"
	.data
	.align	2
	.type	___modver_attr, %object
	.size	___modver_attr, 36
___modver_attr:
	.word	.LC34
	.short	292
	.space	2
	.word	__modver_version_show
	.space	16
	.word	.LC35
	.word	.LC36
	.bss
	.set	.LANCHOR1,. + 0
	.type	__key.10574, %object
	.size	__key.10574, 0
__key.10574:
	.section	.modinfo,"a"
	.type	__UNIQUE_ID_version254, %object
	.size	__UNIQUE_ID_version254, 19
__UNIQUE_ID_version254:
	.ascii	"rockit.version=0.1\000"
	.type	__UNIQUE_ID_license253, %object
	.size	__UNIQUE_ID_license253, 19
__UNIQUE_ID_license253:
	.ascii	"rockit.license=GPL\000"
	.type	__UNIQUE_ID_file252, %object
	.size	__UNIQUE_ID_file252, 37
__UNIQUE_ID_file252:
	.ascii	"rockit.file=drivers/rockit-ko/rockit\000"
	.type	__UNIQUE_ID_author251, %object
	.size	__UNIQUE_ID_author251, 23
__UNIQUE_ID_author251:
	.ascii	"rockit.author=Rockchip\000"
	.section	.rodata.str1.1,"aMS",%progbits,1
.LC0:
	.ascii	"\033[1;32mnode(%s-%d) stream on\033[0m\000"
.LC1:
	.ascii	"\033[1;32mhandle_message: MPI_EVENT_STREAM_ON\033[0"
	.ascii	"m\000"
.LC2:
	.ascii	"node(%s-%d) stream off\000"
.LC3:
	.ascii	"node(%s-%d) flushing\000"
.LC4:
	.ascii	"unbinding source(%s-%d) sink(%s-%d)\000"
.LC5:
	.ascii	"bind source(%s-%d) sink(%s-%d)\000"
.LC6:
	.ascii	"&x->wait\000"
.LC7:
	.ascii	"device(%s) registered\000"
.LC8:
	.ascii	"node(%s-%d) add in watcherdepth(%d)\000"
.LC9:
	.ascii	"node(%s-%d) add in filterdepth(%d)\000"
.LC10:
	.ascii	"node(%s-%d) add out watcherdepth(%d)\000"
.LC11:
	.ascii	"node(%s-%d) add out filterdepth(%d)\000"
.LC12:
	.ascii	"node(%s-%d) del in watcher\000"
.LC13:
	.ascii	"node(%s-%d) del in filter\000"
.LC14:
	.ascii	"node(%s-%d) del out watcher\000"
.LC15:
	.ascii	"node(%s-%d) del out filter\000"
.LC16:
	.ascii	"device(%s) request job\000"
.LC17:
	.ascii	"device(%s) request job for node %d\000"
.LC18:
	.ascii	"node(%s-%d) destroying\000"
.LC19:
	.ascii	"node(%s-%d) created\000"
.LC20:
	.ascii	"device(%s) unregistering\000"
.LC21:
	.ascii	" injected\000"
.LC22:
	.ascii	"\000"
.LC23:
	.ascii	"node(%s-%d) input buf(%d)%s\000"
.LC24:
	.ascii	"\033[1;31mpush in buf queue fail\033[0m\000"
.LC25:
	.ascii	" next\000"
.LC26:
	.ascii	"current\000"
.LC27:
	.ascii	"node(%s-%d) got%s input buf(%d)\000"
.LC28:
	.ascii	"node(%s-%d) got%s output buf(%d)\000"
.LC29:
	.ascii	"node(%s-%d) request buf(%d)\000"
.LC30:
	.ascii	"node(%s-%d) got buf(%d) from pool(%d)\000"
.LC31:
	.ascii	"node(%s-%d) output buf(%d)%s\000"
.LC32:
	.ascii	"\033[1;31mpush out buf queue fail\033[0m\000"
.LC33:
	.ascii	"buf(%d) available for node(%s-%d)\000"
.LC34:
	.ascii	"version\000"
.LC35:
	.ascii	"rockit\000"
.LC36:
	.ascii	"0.1\000"
	.section	___ksymtab_gpl+mpi_dev_create_node_with_params,"a"
	.align	2
	.type	__ksymtab_mpi_dev_create_node_with_params, %object
	.size	__ksymtab_mpi_dev_create_node_with_params, 12
__ksymtab_mpi_dev_create_node_with_params:
	.word	mpi_dev_create_node_with_params
	.word	__kstrtab_mpi_dev_create_node_with_params
	.word	__kstrtabns_mpi_dev_create_node_with_params
	.section	___ksymtab_gpl+mpi_dev_register,"a"
	.align	2
	.type	__ksymtab_mpi_dev_register, %object
	.size	__ksymtab_mpi_dev_register, 12
__ksymtab_mpi_dev_register:
	.word	mpi_dev_register
	.word	__kstrtab_mpi_dev_register
	.word	__kstrtabns_mpi_dev_register
	.section	___ksymtab_gpl+mpi_dev_request_job,"a"
	.align	2
	.type	__ksymtab_mpi_dev_request_job, %object
	.size	__ksymtab_mpi_dev_request_job, 12
__ksymtab_mpi_dev_request_job:
	.word	mpi_dev_request_job
	.word	__kstrtab_mpi_dev_request_job
	.word	__kstrtabns_mpi_dev_request_job
	.section	___ksymtab_gpl+mpi_dev_request_job_for_node,"a"
	.align	2
	.type	__ksymtab_mpi_dev_request_job_for_node, %object
	.size	__ksymtab_mpi_dev_request_job_for_node, 12
__ksymtab_mpi_dev_request_job_for_node:
	.word	mpi_dev_request_job_for_node
	.word	__kstrtab_mpi_dev_request_job_for_node
	.word	__kstrtabns_mpi_dev_request_job_for_node
	.section	___ksymtab_gpl+mpi_dev_run_job,"a"
	.align	2
	.type	__ksymtab_mpi_dev_run_job, %object
	.size	__ksymtab_mpi_dev_run_job, 12
__ksymtab_mpi_dev_run_job:
	.word	mpi_dev_run_job
	.word	__kstrtab_mpi_dev_run_job
	.word	__kstrtabns_mpi_dev_run_job
	.section	___ksymtab_gpl+mpi_dev_unregister,"a"
	.align	2
	.type	__ksymtab_mpi_dev_unregister, %object
	.size	__ksymtab_mpi_dev_unregister, 12
__ksymtab_mpi_dev_unregister:
	.word	mpi_dev_unregister
	.word	__kstrtab_mpi_dev_unregister
	.word	__kstrtabns_mpi_dev_unregister
	.section	___ksymtab_gpl+mpi_node_add_in_filter,"a"
	.align	2
	.type	__ksymtab_mpi_node_add_in_filter, %object
	.size	__ksymtab_mpi_node_add_in_filter, 12
__ksymtab_mpi_node_add_in_filter:
	.word	mpi_node_add_in_filter
	.word	__kstrtab_mpi_node_add_in_filter
	.word	__kstrtabns_mpi_node_add_in_filter
	.section	___ksymtab_gpl+mpi_node_add_in_watcher,"a"
	.align	2
	.type	__ksymtab_mpi_node_add_in_watcher, %object
	.size	__ksymtab_mpi_node_add_in_watcher, 12
__ksymtab_mpi_node_add_in_watcher:
	.word	mpi_node_add_in_watcher
	.word	__kstrtab_mpi_node_add_in_watcher
	.word	__kstrtabns_mpi_node_add_in_watcher
	.section	___ksymtab_gpl+mpi_node_add_out_filter,"a"
	.align	2
	.type	__ksymtab_mpi_node_add_out_filter, %object
	.size	__ksymtab_mpi_node_add_out_filter, 12
__ksymtab_mpi_node_add_out_filter:
	.word	mpi_node_add_out_filter
	.word	__kstrtab_mpi_node_add_out_filter
	.word	__kstrtabns_mpi_node_add_out_filter
	.section	___ksymtab_gpl+mpi_node_add_out_watcher,"a"
	.align	2
	.type	__ksymtab_mpi_node_add_out_watcher, %object
	.size	__ksymtab_mpi_node_add_out_watcher, 12
__ksymtab_mpi_node_add_out_watcher:
	.word	mpi_node_add_out_watcher
	.word	__kstrtab_mpi_node_add_out_watcher
	.word	__kstrtabns_mpi_node_add_out_watcher
	.section	___ksymtab_gpl+mpi_node_bind,"a"
	.align	2
	.type	__ksymtab_mpi_node_bind, %object
	.size	__ksymtab_mpi_node_bind, 12
__ksymtab_mpi_node_bind:
	.word	mpi_node_bind
	.word	__kstrtab_mpi_node_bind
	.word	__kstrtabns_mpi_node_bind
	.section	___ksymtab_gpl+mpi_node_buffer_in,"a"
	.align	2
	.type	__ksymtab_mpi_node_buffer_in, %object
	.size	__ksymtab_mpi_node_buffer_in, 12
__ksymtab_mpi_node_buffer_in:
	.word	mpi_node_buffer_in
	.word	__kstrtab_mpi_node_buffer_in
	.word	__kstrtabns_mpi_node_buffer_in
	.section	___ksymtab_gpl+mpi_node_buffer_out,"a"
	.align	2
	.type	__ksymtab_mpi_node_buffer_out, %object
	.size	__ksymtab_mpi_node_buffer_out, 12
__ksymtab_mpi_node_buffer_out:
	.word	mpi_node_buffer_out
	.word	__kstrtab_mpi_node_buffer_out
	.word	__kstrtabns_mpi_node_buffer_out
	.section	___ksymtab_gpl+mpi_node_del_in_filter,"a"
	.align	2
	.type	__ksymtab_mpi_node_del_in_filter, %object
	.size	__ksymtab_mpi_node_del_in_filter, 12
__ksymtab_mpi_node_del_in_filter:
	.word	mpi_node_del_in_filter
	.word	__kstrtab_mpi_node_del_in_filter
	.word	__kstrtabns_mpi_node_del_in_filter
	.section	___ksymtab_gpl+mpi_node_del_in_watcher,"a"
	.align	2
	.type	__ksymtab_mpi_node_del_in_watcher, %object
	.size	__ksymtab_mpi_node_del_in_watcher, 12
__ksymtab_mpi_node_del_in_watcher:
	.word	mpi_node_del_in_watcher
	.word	__kstrtab_mpi_node_del_in_watcher
	.word	__kstrtabns_mpi_node_del_in_watcher
	.section	___ksymtab_gpl+mpi_node_del_out_filter,"a"
	.align	2
	.type	__ksymtab_mpi_node_del_out_filter, %object
	.size	__ksymtab_mpi_node_del_out_filter, 12
__ksymtab_mpi_node_del_out_filter:
	.word	mpi_node_del_out_filter
	.word	__kstrtab_mpi_node_del_out_filter
	.word	__kstrtabns_mpi_node_del_out_filter
	.section	___ksymtab_gpl+mpi_node_del_out_watcher,"a"
	.align	2
	.type	__ksymtab_mpi_node_del_out_watcher, %object
	.size	__ksymtab_mpi_node_del_out_watcher, 12
__ksymtab_mpi_node_del_out_watcher:
	.word	mpi_node_del_out_watcher
	.word	__kstrtab_mpi_node_del_out_watcher
	.word	__kstrtabns_mpi_node_del_out_watcher
	.section	___ksymtab_gpl+mpi_node_destroy,"a"
	.align	2
	.type	__ksymtab_mpi_node_destroy, %object
	.size	__ksymtab_mpi_node_destroy, 12
__ksymtab_mpi_node_destroy:
	.word	mpi_node_destroy
	.word	__kstrtab_mpi_node_destroy
	.word	__kstrtabns_mpi_node_destroy
	.section	___ksymtab_gpl+mpi_node_enable_auto_streamon,"a"
	.align	2
	.type	__ksymtab_mpi_node_enable_auto_streamon, %object
	.size	__ksymtab_mpi_node_enable_auto_streamon, 12
__ksymtab_mpi_node_enable_auto_streamon:
	.word	mpi_node_enable_auto_streamon
	.word	__kstrtab_mpi_node_enable_auto_streamon
	.word	__kstrtabns_mpi_node_enable_auto_streamon
	.section	___ksymtab_gpl+mpi_node_flush,"a"
	.align	2
	.type	__ksymtab_mpi_node_flush, %object
	.size	__ksymtab_mpi_node_flush, 12
__ksymtab_mpi_node_flush:
	.word	mpi_node_flush
	.word	__kstrtab_mpi_node_flush
	.word	__kstrtabns_mpi_node_flush
	.section	___ksymtab_gpl+mpi_node_force_lost_frame,"a"
	.align	2
	.type	__ksymtab_mpi_node_force_lost_frame, %object
	.size	__ksymtab_mpi_node_force_lost_frame, 12
__ksymtab_mpi_node_force_lost_frame:
	.word	mpi_node_force_lost_frame
	.word	__kstrtab_mpi_node_force_lost_frame
	.word	__kstrtabns_mpi_node_force_lost_frame
	.section	___ksymtab_gpl+mpi_node_get_in_buffer,"a"
	.align	2
	.type	__ksymtab_mpi_node_get_in_buffer, %object
	.size	__ksymtab_mpi_node_get_in_buffer, 12
__ksymtab_mpi_node_get_in_buffer:
	.word	mpi_node_get_in_buffer
	.word	__kstrtab_mpi_node_get_in_buffer
	.word	__kstrtabns_mpi_node_get_in_buffer
	.section	___ksymtab_gpl+mpi_node_get_out_buffer,"a"
	.align	2
	.type	__ksymtab_mpi_node_get_out_buffer, %object
	.size	__ksymtab_mpi_node_get_out_buffer, 12
__ksymtab_mpi_node_get_out_buffer:
	.word	mpi_node_get_out_buffer
	.word	__kstrtab_mpi_node_get_out_buffer
	.word	__kstrtabns_mpi_node_get_out_buffer
	.section	___ksymtab_gpl+mpi_node_pick_in_buffer,"a"
	.align	2
	.type	__ksymtab_mpi_node_pick_in_buffer, %object
	.size	__ksymtab_mpi_node_pick_in_buffer, 12
__ksymtab_mpi_node_pick_in_buffer:
	.word	mpi_node_pick_in_buffer
	.word	__kstrtab_mpi_node_pick_in_buffer
	.word	__kstrtabns_mpi_node_pick_in_buffer
	.section	___ksymtab_gpl+mpi_node_pick_out_buffer,"a"
	.align	2
	.type	__ksymtab_mpi_node_pick_out_buffer, %object
	.size	__ksymtab_mpi_node_pick_out_buffer, 12
__ksymtab_mpi_node_pick_out_buffer:
	.word	mpi_node_pick_out_buffer
	.word	__kstrtab_mpi_node_pick_out_buffer
	.word	__kstrtabns_mpi_node_pick_out_buffer
	.section	___ksymtab_gpl+mpi_node_release_buffer_flag,"a"
	.align	2
	.type	__ksymtab_mpi_node_release_buffer_flag, %object
	.size	__ksymtab_mpi_node_release_buffer_flag, 12
__ksymtab_mpi_node_release_buffer_flag:
	.word	mpi_node_release_buffer_flag
	.word	__kstrtab_mpi_node_release_buffer_flag
	.word	__kstrtabns_mpi_node_release_buffer_flag
	.section	___ksymtab_gpl+mpi_node_request_buf,"a"
	.align	2
	.type	__ksymtab_mpi_node_request_buf, %object
	.size	__ksymtab_mpi_node_request_buf, 12
__ksymtab_mpi_node_request_buf:
	.word	mpi_node_request_buf
	.word	__kstrtab_mpi_node_request_buf
	.word	__kstrtabns_mpi_node_request_buf
	.section	___ksymtab_gpl+mpi_node_set_frame_rate,"a"
	.align	2
	.type	__ksymtab_mpi_node_set_frame_rate, %object
	.size	__ksymtab_mpi_node_set_frame_rate, 12
__ksymtab_mpi_node_set_frame_rate:
	.word	mpi_node_set_frame_rate
	.word	__kstrtab_mpi_node_set_frame_rate
	.word	__kstrtabns_mpi_node_set_frame_rate
	.section	___ksymtab_gpl+mpi_node_set_params,"a"
	.align	2
	.type	__ksymtab_mpi_node_set_params, %object
	.size	__ksymtab_mpi_node_set_params, 12
__ksymtab_mpi_node_set_params:
	.word	mpi_node_set_params
	.word	__kstrtab_mpi_node_set_params
	.word	__kstrtabns_mpi_node_set_params
	.section	___ksymtab_gpl+mpi_node_stream_pause,"a"
	.align	2
	.type	__ksymtab_mpi_node_stream_pause, %object
	.size	__ksymtab_mpi_node_stream_pause, 12
__ksymtab_mpi_node_stream_pause:
	.word	mpi_node_stream_pause
	.word	__kstrtab_mpi_node_stream_pause
	.word	__kstrtabns_mpi_node_stream_pause
	.section	___ksymtab_gpl+mpi_node_streamoff,"a"
	.align	2
	.type	__ksymtab_mpi_node_streamoff, %object
	.size	__ksymtab_mpi_node_streamoff, 12
__ksymtab_mpi_node_streamoff:
	.word	mpi_node_streamoff
	.word	__kstrtab_mpi_node_streamoff
	.word	__kstrtabns_mpi_node_streamoff
	.section	___ksymtab_gpl+mpi_node_streamon,"a"
	.align	2
	.type	__ksymtab_mpi_node_streamon, %object
	.size	__ksymtab_mpi_node_streamon, 12
__ksymtab_mpi_node_streamon:
	.word	mpi_node_streamon
	.word	__kstrtab_mpi_node_streamon
	.word	__kstrtabns_mpi_node_streamon
	.section	___ksymtab_gpl+mpi_node_unbind,"a"
	.align	2
	.type	__ksymtab_mpi_node_unbind, %object
	.size	__ksymtab_mpi_node_unbind, 12
__ksymtab_mpi_node_unbind:
	.word	mpi_node_unbind
	.word	__kstrtab_mpi_node_unbind
	.word	__kstrtabns_mpi_node_unbind
	.section	__modver,"a"
	.align	2
	.type	__modver_attr, %object
	.size	__modver_attr, 4
__modver_attr:
	.word	___modver_attr
	.ident	"GCC: (crosstool-NG 1.24.0) 8.3.0"
	.section	.note.GNU-stack,"",%progbits
